apiVersion: v1
kind: Service
metadata:
  name: wyoming-whisper
  namespace: wyoming-whisper
spec:
  ports:
    - port: 10300
      targetPort: 10300
      protocol: TCP
      name: wyoming
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: wyoming-whisper
  namespace: wyoming-whisper
  labels:
    kubernetes.io/service-name: wyoming-whisper
addressType: IPv4
ports:
  - port: 10300
    protocol: TCP
    name: wyoming
endpoints:
  - addresses:
      - "192.168.1.105"
