apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: external-dns
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      serviceAccountName: external-dns
      containers:
        - name: external-dns
          image: registry.k8s.io/external-dns/external-dns:v0.15.1
          args:
            - --source=ingress # enable both service and ingress sources
            - --domain-filter=alexnorum.com # (optional) limit to only example.com domains; change to match the zone created above.
            - --policy=sync
            - --provider=cloudflare
            - --cloudflare-dns-records-per-page=5000 # (optional) configure how many DNS records to fetch per request
          env:
          - name: CF_API_TOKEN
            valueFrom:
              secretKeyRef:
                name: cloudflare-api-key
                key: apiKey