apiVersion: apps/v1
kind: Deployment
metadata:
  name: mealie
  namespace: mealie
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mealie
  template:
    metadata:
      labels:
        app: mealie
    spec:
      containers:
        - name: mealie
          image: ghcr.io/mealie-recipes/mealie:v2.8.0
          ports:
            - containerPort: 9000
          resources:
            limits:
              memory: "1000Mi"
            requests:
              memory: "500Mi"
              cpu: "200m"
          env:
            - name: ALLOW_SIGNUP
              value: "false"
            - name: ALLOW_PASSWORD_LOGIN
              value: "false"
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "America/Los_Angeles"
            - name: BASE_URL
              value: "https://mealie.alexnorum.com"
            # Authentik OIDC Configuration
            - name: OIDC_AUTH_ENABLED
              value: "True"
            - name: OIDC_PROVIDER_NAME
              value: "authentik"
            - name: OIDC_CONFIGURATION_URL
              value: "https://sso.alexnorum.com/application/o/mealie/.well-known/openid-configuration"
            - name: OIDC_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: mealie-authentik-creds
                  key: client-id
            - name: OIDC_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: mealie-authentik-creds
                  key: client-secret
            - name: OIDC_SIGNUP_ENABLED
              value: "true"
            - name: OIDC_USER_GROUP
              value: "mealie-users"
            - name: OIDC_ADMIN_GROUP
              value: "mealie-admins"
            - name: OIDC_AUTO_REDIRECT
              value: "false"
            - name: OIDC_REMEMBER_ME
              value: "true"
            # SQLite specific configuration
            - name: DB_ENGINE
            # OpenAI
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: openai-mealie-key
                  key: openai-api-key
          volumeMounts:
            - name: mealie-data
              mountPath: /app/data
      volumes:
        - name: mealie-data
          persistentVolumeClaim:
            claimName: mealie-data