---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mealie-authentik-creds
  namespace: mealie
spec:
  encryptedData:
    client-id: AgBDqlvbfohFJO7r4/Jzuq9uI6AFUsVDLuC6EVH9N2/ZO7A2b4RbdQmEBJRNpQSAHtnljssnlCxDguE92nW4YEcwyb72y4wNnRdiCU/JjMnJ5urOHPNJXWWR+fT51WrlIFWBoMt2M0OkWX6nyiCryJEPFZm1oqt16TYO41hn19vFPxeIw5N7s8+S7byPhy6T+I0mPwn8zVc1MinzW+JaOoWFbSvV5NoGKF66Blub0K0UlOm07iyonGiJ0nDrff1ZK+jKRoEngRtA+bHbObqUvjX/seQOGzuwlSVy/t84OP/OCUd4eh755ZqDl0KW+ykUzfAuenh3MwE922JhWkZR7R+IQBWqZUz+mFLWkjSCvYGHtldhqDtu9Nkfnml7w4bKdLI4RTOGpya8CYvuUFz00akTQ1F7YwCi/EsstzzSkVxs2Mw0ZQO3MUWjiqRe1FamMRW1kIhzGArH9njWtupERp7FsibdVkzT66cbYHLpq/FYOcSWir5o1cXX5bMgAN5+g82g1jcNNDioqwFSzTVqWokcxQHWC6X6mqR1cUTB3tO020JpyzXn3C9nX0Om9NXRyjlZ0xraNc2Cv+eYnPQLZIhR1tomS07TzDTtwwa4iN4nrd3X0vYHnSYqcViodFs4a64qkQzD28aiBqtSDqmzQ8QQwTQ+oKeMGPSwZ8AsNItYu0Ef3iwDW5UWN5L3KIKcpNa333r+bvXwOKW4++7gi9b1bOdiNksPNiV/hg1zljU5jgHMKzLuN6Dt
    client-secret: AgBezyH2+gZ4GPHfTninlD7gY3ncXpJEqcvQDJBWd9wmgGX8xVnamRR1QLl/5bv7DYhmwC1xuP5qocKZFlmyMTz13mxyaRJR9ugvs2XCr+ForX46Ap+9IA24ZiFvfhbN//2DOZmC+daWptn1geQRX8+AUiectPIcmQdYqTixjCWvTqL9YfIR/c6s5+3QSbyg+P5K/6ZBDK2XVNfpFbrGkOQCwaNt999mTQ6KtJRNq4Q9rCbkk4UAxYm+eTbO3OXmte6yk72Ysdjg7f3Bzz7lt63SohIlPoQLD9jpol7iS87Ynjh2unKGHyKeB/gJdCPQeUKZYaNPYhbDJnmaB3mvlO7nnFTZ3hyK4lJ8GqXazy+wUu1gO4VHSCWgDsmHJxva0gOuu/q7hWd/HsZdytf0HDZfXR+1De6RqoLvBqFkbaiFe9jGAbp5G8qkh0PKB8gFGqwUkr0G5x3SiuytR1H+qNOxpsYLzdvk65WgD3f0NNWYCPcgSKoTPoQvg5QTwT3KQREDZmp7mWGukwHFW+YYBMupHXjtSyoZtRBsH6RoSrISH0/bCTTSyJUJBpDhXMvbCOBSgIpF/h6Do9g6lj2a3HJVx+VZa4t3dDaa+NgWqmL1QemtaAHJ1AKjg9tYNv93ox9FsYXcTw+rffghLrKJi5XGzzfYUe0HxRpmWZYwBiRe6dAbHUCSJrgtDXOFLR4U+Rmnr/hCGRAiM2lUeMeC9YCrv980NYNnNZ1l5j/c+aH/QvyUTYQ1rkyNaJ+90CjYSQA4J3daFdjKJI/so0npkMtzQgxEsy030dbUH9tAlxhMdBavQPv56KQZ4hehOnZBX56kgwT65Ghjfhl2FkV57HNDhN8ofAZlZj3sl54uBRuQ+w==
  template:
    metadata:
      creationTimestamp: null
      name: mealie-authentik-creds
      namespace: mealie
    type: Opaque
