apiVersion: ENC[AES256_GCM,data:r6M=,iv:ucxPRLqxQcqI9OI+Wd/XT4syQ7gF3Y1IEjk0Vxg71Wc=,tag:LdFHOFUtb63yjlvzRxhXkA==,type:str]
kind: ENC[AES256_GCM,data:LJyE4msv,iv:j3xb2+87/gHD3NM6VYJ8sWrN5RJyFv28I6g4QSc7qSg=,tag:FXaK7ETAu4A2Q/qpKmfk1Q==,type:str]
metadata:
    name: ENC[AES256_GCM,data:a/yYm0B+VvhNMsUa3aosvmcsGj46nQ==,iv:kUMOAfzNzOfZt7o1VuYnwonklXCe48SViCXarFNi6Bo=,tag:JRkoUXGV26VG6RSDIO3oOw==,type:str]
    namespace: ENC[AES256_GCM,data:QLhia7JH,iv:pue5MM9ZL2zGsRrQToPdRBHeEReHW01aIOAyXITct9A=,tag:6uylYTF9HcJ8QevzE4xoUA==,type:str]
type: ENC[AES256_GCM,data:Y3qaiF0h,iv:SQ9d2ZIuWkSZg1Xu5CV9cgOmL59SWrBphWY9tdVA+uI=,tag:u1IZmBkG9e02/Dm+d3nhmg==,type:str]
stringData:
    client-id: ENC[AES256_GCM,data:bA8diLsCDhHcNU91yYKC/QUexyCn4KF/r6LUCMDZKBIKgW8=,iv:sZgonZHSwMyXNWRpN7XM6QN1Jmt9mf/bjiiC1Ck5Ock=,tag:KE9vB2GzO4C6yBOJazNFVA==,type:str]
    client-secret: ENC[AES256_GCM,data:2X4sZ3R2NYsqmV8WwAtw4ZOMVTQWFtyj55S1Z34rKbHxZUc=,iv:niTgffg+vL/OpXHDDz9JmsUqZjiuAZn2Gr4Nfgcx+uk=,tag:8ViCntcg+k2hot0A/GXyCA==,type:str]
sops:
    age:
        - recipient: age139l36fqzkzsl9rs7n5wxn9yngs0mdt06taktet96gm7uk9gq9aqqxukvps
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlMEJDU3ROaVpQT09rWHA5
            YU1CUUthL2FONnhQcEZYRmIwNzZ6RG1kQWtvCmlzbFcwR3c2aEtJZWNzeXM5SEFr
            VTdaUnRVQTdXTEQ2L0R0YlVXR0ZmSzAKLS0tIDB1a1JySzU4a2plQkQxYjYxUWN4
            Z0hkQXY4ZjJHQ3BrM25KdWo4Qkx2VXcKdePb6OmcCIUzqiVaTIP/OutHqmQMGacq
            uypM7CHaG65nX9pszaMdD00Zl4NmQEl1UjAAEsbdC7YR38CfXIPf1Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-23T05:11:56Z"
    mac: ENC[AES256_GCM,data:e3Tlzq7K+t2jrH7SDpO2b/7ZKiiyqc0oxd4//6rpDth7jM6RM/Uf7U6o7gnfkZxpTyddS6sKqFkqJFZ0JZgoP16in3PEX/q3zSjVZNsfA4OJZPKo5pKtjAGi3E1EwtvyHeYM0wBZsqXEgFa5jXYFh2bTV3kCpEKY8QYxxLx3u7g=,iv:Klwkk0OqXYtdth0pOsUCuceY0FkiZW9f+OW+E6SBpNU=,tag:HmRWRXqAddKrCK7Dw7jcNw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
