apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: thehoytwire

resources:
- namespace.yaml
- deployment.yaml
- ingress.yaml
images:
- name: ghcr.io/anorum/thehoytwire:latest
  newName: ghcr.io/anorum/thehoytwire
  newTag: latest
