apiVersion: ENC[AES256_GCM,data:voU=,iv:hlo1QFjpXTFGXeALerhn3x7a8kSKukXrSUrHH2bSYyw=,tag:fRZivhWK8WRgNy61VERdbg==,type:str]
kind: ENC[AES256_GCM,data:saQVJUzl,iv:VZdePhRzHO5HlWfBWvKPikGNT0qIKknM4GlyRtJXoWk=,tag:NFOR12augyQZ18youYwncA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Xsvte5lrk6UKuir7+Br7uVPTuupbkQ==,iv:vt9N2QggbRa2/hxO1oH4mP+2peTgN/qCMYtCkp3sD2w=,tag:AUhmOQy2XDLFJLgUxQgYMQ==,type:str]
    namespace: ENC[AES256_GCM,data:XHQYq8sl,iv:6I54GawgNI6p8/PFSPctJ7IXxxBj/qtB6WcC49Oq6Fk=,tag:bkY/loq1qHSQPBnVZR15nA==,type:str]
type: ENC[AES256_GCM,data:2TdtrFpV,iv:YHPVk2lYllmZKnR0Rb9KNDxTZxaLSPxIpcndms1uBvk=,tag:+cfGiGX40gAdunwQseSwrg==,type:str]
stringData:
    aws-access-key-id: ENC[AES256_GCM,data:DBiAvJ3xGSv23THQ2TkQSLbCBgg=,iv:HAVM30woTzm9HuRvRyU2pQ0BITpR8sBGTiZ4sic5Z2o=,tag:Gqq/vakeXMH6f7OSSTSYCw==,type:str]
    aws-secret-access-key: ENC[AES256_GCM,data:HOicwnO47qlkxvQTRa8X0X5RIp/2HFb7qX1G6NIeWVwUdwS6CpoadQ==,iv:uLeDXL60GxmumOeE9Z7uw5O1XCu+ENMhTLOvVoR/ZFY=,tag:wW/GxF5deevIE9cqgRIH/w==,type:str]
    aws-region: ENC[AES256_GCM,data:2Ny/ckf2p9eH,iv:WmRed1f/tYmugd6eL8XtyjpJcAP8XR5Umk0Q/sEvk2A=,tag:dkNgjTPYjD0gsvJf8ftFXw==,type:str]
sops:
    age:
        - recipient: age139l36fqzkzsl9rs7n5wxn9yngs0mdt06taktet96gm7uk9gq9aqqxukvps
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFN2FVRDkwcEtrRWRpbytL
            L3lwZlRoZ0JDQWhlN0ZGdFcyT0lIRVRjYmxZCkZDUXZsZFB0Mngwb283TWlzMFRX
            ZGVwSE9saUd1WEtrakpkL1lTa1F1Z1EKLS0tIGxBUFFMQllkUFVGT3FESEl5Lzh3
            UEZrNGh1dkp6VUFwbFVoOWdwb2x6b3MKHuKjbgTMlyenIUB7momZSbf/jQikohXH
            kkc/XS8XpwToo8mnMVHJ4s7P+4irqdMemoW+/8K3YWBLzL5OUEAhaA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-08T06:02:24Z"
    mac: ENC[AES256_GCM,data:jNsC+vnP7Ldd/w3nUBo8/GciFIXFCxW+DniYnT7TEXaXc3RlAKqnNyOkT8+v3TSsWHBjL31A7crdjx9uEWgWXGWCsAiHtWkGM0n+2usrIuIAO9nCSJlTQHgfdBvhbZxcwIRkPio9X8+uLOk0kuqpXYcqCbenFmLcMK7W3aH4JMk=,iv:a71u8I27UxVQxE5rwK9sBzLxLkni1qkSBaOnDGhZ2vI=,tag:EMTdnol6vtlf5mi+qZ/4Iw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
