all:
  vars:
    ansible_user: anorum
    ansible_ssh_private_key_file: ~/.ssh/rpi_key
  hosts:
    swagman-1:
      ansible_host: 192.168.1.101
    swagman-2:
      ansible_host: 192.168.1.102

  children:
    masters:
      hosts:
        swagman-1:
    workers:
      hosts:
        swagman-2:
    mac_mini:
      hosts:
        mac-mini:
          ansible_host: 192.168.1.168
          ansible_connection: local
    voice_satellite:
      hosts:
        voice-satellite:
          ansible_host: voice-satellite.local  # update to static IP after DHCP assignment