apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: external-secrets

resources:
  - namespace.yaml

labels:
- pairs:
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/instance: external-secrets

helmCharts:
  - name: external-secrets
    repo: https://charts.external-secrets.io
    releaseName: external-secrets
    namespace: external-secrets
