apiVersion: ENC[AES256_GCM,data:wF4=,iv:asuAglkAeXX1EK2ttwjuOU4XaeafjdDSWCOeuvzpSzY=,tag:xoXz6L2RqVTsAyr+t1CuZA==,type:str]
kind: ENC[AES256_GCM,data:VR/xkIEN,iv:J672x2j3wPljDvqzKy84XehM+cmdgsSzwiVUT10Ba9g=,tag:+3362VCx0vkvbEYMm+Mf1A==,type:str]
metadata:
    name: ENC[AES256_GCM,data:StYO7prYU5cYcl47N4+z,iv:BDtKyjVADVU7GxmYEBqAcXoXNUZ4hIUth0xLHST/5bM=,tag:QCfWTsD51HUA1ldITg1F1A==,type:str]
    namespace: ENC[AES256_GCM,data:dBGGxOgEu/m3PQ==,iv:fcIOBW9DMBiItYfE8CWRtQP2JXmMXQzy5++vGdKzLbQ=,tag:Yd/y/T0gB3OhFBxNLmuhjw==,type:str]
type: ENC[AES256_GCM,data:a3sI1r/1,iv:V2RIwm6nL4IJf4e0vNciiaK22JMVKZTlInwOY+I6tQc=,tag:O4Ca5mNsoBPxjKRAOutCJg==,type:str]
stringData:
    webhook-url: ENC[AES256_GCM,data:FyxCZEN4haSUMU4pG8apFfr/Okiogw4xqVeyXTupQvVX0TLArbsddB30vpMRBOQhOlKR9XISgTsS+U/yw/I89wtb6APyPBd0jCs0pWfI1v0YjE/72qkY5BWXFysTFyrVLhtf1mm/xmbfN//+MdF3B1ew4jf9YH4wQtDU2Cww6w==,iv:HrLCHdrqHSGEck5SOgx28gNNjctcIFXgrSmjLYxWMPI=,tag:UnC1eyLZpktL3gQUtZPMBw==,type:str]
sops:
    age:
        - recipient: age139l36fqzkzsl9rs7n5wxn9yngs0mdt06taktet96gm7uk9gq9aqqxukvps
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByRWh0WDZwYnRoc1ltV1hJ
            YUY1V283R05lQ1cyZmMwdU05VEdaNEpDTjMwClkyMDgrV0FMUzJRY3ZVelRuV2Zt
            UHBEK203RFFWTWMrTUcwbTIrNlF6bUUKLS0tIFVybEl5b2JPZ29ZUmhjUEFRYmxD
            cHkra1BzUXB3Q1VFNnhxdlhyNkJpN28KvMl1QYWLNVqEhsfA9S13x7EYjPg91FxA
            5hNs7F8BQHNpoQrCdzJYvtpg3IGS0QJ2q3NVVDBHpAH2++FtGc4O2g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-08T01:02:00Z"
    mac: ENC[AES256_GCM,data:M9rp/JLynUnM14+nkM4Okl0Xpb7xk9ipCvN+Gm8TgR3x/dfXd7D9+Hjslpx32EmHJzNxbIeyBZzWTXDep0/OM8COAw7aiBKtVndKdwUa9FYsMBtcUgsv+ucNF3V0NWfSi59cCJtAYRSiPZTmzQlTmg+uhFLbWGaiYElKyV7kRk0=,iv:2EfA3mIRHJ0Wci/fhdeWOIJ8oXnzuSzAKdFlKW4Xkg8=,tag:JSP9vp2EsHEbv5/gWqyudg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
