apiVersion: ENC[AES256_GCM,data:ja4=,iv:VK9iXMIUK51EVhBazueLiHSq0f6Fnw7Ob/YW4dHO5G8=,tag:QQosgyrO9vpSUzg9loff9Q==,type:str]
kind: ENC[AES256_GCM,data:NHPaYIBG,iv:YUbWkVtmh5MAPY8bFtxBme7poJgfrTSzdb6iX4jK+D0=,tag:XLNPZoa4mNhQaV5m2rTzLQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:n/srZq5nwpL4mFNER9gn,iv:qJc25nNPQqqXTtHjwkiDNN2CmW60Oe5FLji5tRm5J+c=,tag:o1jf1xkBAUFad8IBwSG4SQ==,type:str]
    namespace: ENC[AES256_GCM,data:szud/oGdCrSaeA==,iv:hovS9p1lrUDc/IVKaRHrXho6iT1Fjpk1s0O3lHhZnCU=,tag:SL07fqQDqcdbcXfQr/vUDw==,type:str]
type: ENC[AES256_GCM,data:QiEKy0I4,iv:ORB1taVI2msWY2AT3RUUqhrAngCXn71zzAj0sgwCQyo=,tag:tzFYN18De356Vyv9WeTTiA==,type:str]
stringData:
    webhook-url: ENC[AES256_GCM,data:U8MB5LJzUWpw2ALFgffBW348Q3cFWEdnERA8vo6LVWkoKclhamqKY5JCQvcYlspDXirc2t1t2epOLFGXralrpsE7zh3bhs7HrPvWk0zg2NXJRHBdPtfNyqku2oUKBL8t5UUxngWHTkTy2dPvImjJLfLTlMw0f52pnA==,iv:a7/chAG0VH5mYhCYAEcWJvwuQchbcgA6JUya+WyCHbU=,tag:CRA6oLku5DL2dhmSFl/jpg==,type:str]
sops:
    age:
        - recipient: age139l36fqzkzsl9rs7n5wxn9yngs0mdt06taktet96gm7uk9gq9aqqxukvps
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHSDFNWHpGMlk0cVNYOUox
            QnJ2N1E1Vmw2blQ0Vmt5Q3dsVlNBUTVLd1c4CmJkRVhCMFg2SmlOL1Jwd1JvQnN5
            clNBTDJETCtSeEtHb0NxenU3L0ZGbDAKLS0tIHRqcWtrb0xwYlFOKy9wM3RyUjcx
            MGNvVVVHaGxKVjdlTnVkc2NYTTg4WlkKK6OSd9Zand41AAWKJ4PkWhNGb0tA4YoW
            8Zo5acNlPdqSCLsfHJosxKdY0b9zMPmSCyM2TdAFq4aqIZ8SfdsUwQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-07T01:57:28Z"
    mac: ENC[AES256_GCM,data:vJvT6wKBx1t4NogQFKLRamgDAy5UklkI5crS4dCv6fhVwP64WjAJ9YNl6g3T907MBiSlToy/yKOf7refd2IBTGOwrUXOw3RWTPodTaJ2LV5P7PjbFOcrTPmU6tFxBlr7nvVGqVbpxbl/2b6bUK/aXZNOSCEVzk+lttpAwhu1QWY=,iv:DSvINWYqEb5tWRlL5uK+P/fw0vRSpbS3ZxtiWJFoK7A=,tag:8BU3z4sd0zrjvRn1K8XA5w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
