apiVersion: ENC[AES256_GCM,data:V5M=,iv:uAI4y213XFLjX8yP0DUBqV8MlByloReq52UDOO0yrFY=,tag:UB1fcEILLAK0HGUWT6SRDA==,type:str]
kind: ENC[AES256_GCM,data:zRI8yyis,iv:Fpd4L6PixxS9ZnFSC15iyVK8HmqsOTwEJgqEFlage+8=,tag:UI5slHezbFQl/zC9V3R1qw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:guFQNs/kimksHClrs/HmpCAh3Ow=,iv:ZFGv1tO0wSjEWWxaqwUncdC78JRaDWH0ahTT1o91c4k=,tag:7v5yOZR7hA2H5BoG+HDqMQ==,type:str]
    namespace: ENC[AES256_GCM,data:wTqsbQw4As4W1w==,iv:IITiSuo6VMUn79TFmpOejlyD1r9LEBsLMX8GAKtrSKs=,tag:4vnCqZj6Q1AJ5t7j6XyClg==,type:str]
stringData:
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:7YZifrS8GCB8+j6Jt+CsluQT1UyvLKMo4wbMNlD0OmfhowLgncg/HHqLyStonv0OUlouDCcD,iv:YVUZBDqxb4zhfmdWIuzvB023jtJRhOAZOPZlENWjtx0=,tag:BpMmH2y902ou8KLkx2HeSw==,type:str]
sops:
    age:
        - recipient: age139l36fqzkzsl9rs7n5wxn9yngs0mdt06taktet96gm7uk9gq9aqqxukvps
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIbUFObFZEZEM1MThOUHEw
            c0luaE1JaXhCejhHMEFMb1BKYWp4MFk0QXhBCitLNjV6MWpzTmRObXRKK1I0NXkr
            SytIZjAzdWIzS2ZtaW1TTm42TkVFRWMKLS0tIFRtZEY0STliSDFGVmRnL2dNOWVW
            ZU05U0NlZk02b1M1SCtPa1pndkY4d0kKzSsZnCTOLrP5RsIB/fb6709LCQD9+6v/
            tcy6y+at4FNQoy0s5ijTA9+9KpKfrhxYabaQfU2FVziq2YzpoM2Ebg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-07T23:36:42Z"
    mac: ENC[AES256_GCM,data:TNDqezVReTlZ563kT2f6lZO8ACyLPUHQxVMyqgqXCr0jeBqCBoy9FFVeU7VT6XwoMyDDxYNe6weoqq2wTZodzoljCsvBmTzdtzZyYANYBftAhwaXT2vutQSmQZiwCYuthV7ucgOM9HKp6hK1D9xgX583W5CjHRbow9k8sCVdguw=,iv:VgDJIvpAdb0KW4+nDQ3Qx0qfrOzouQ9EFb0a0En8aAc=,tag:tzehZhpu+Aeyvw+tYx8J9g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
