apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: ha-scrape-secret-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - ha-scrape-config.enc.yaml
