apiVersion: ENC[AES256_GCM,data:9Tw=,iv:fXRDX93hs9H+WGP+b+qoCTrLK94zoL59rdSCZJFzrdM=,tag:Fe29StUu6S5dgZJIZBiWrA==,type:str]
kind: ENC[AES256_GCM,data:UX7HxsVf,iv:/eT/5eMAI/nR/IR9UCpkobrtyS9eoNn3c0iyGchEH9c=,tag:rvePBPlST4nM58VlZsb5hw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:21HE0zt5bM51OOsr8H+lTg==,iv:4JWrNwOOx1fhjHknmqK1ONo5jhqTaHzzd4RJxwSdWj4=,tag:wK6XlvfalFKHo1cdFfdOPw==,type:str]
    namespace: ENC[AES256_GCM,data:VJ3gaIBPfuRT/g==,iv:1WS2lHmks7SgPGEgsobsSB8CmPHnCBzuMw6yPDqeY28=,tag:9SQMwBFwVykvNO02coUjHA==,type:str]
type: ENC[AES256_GCM,data:yVed3u9T,iv:xtZOWg9W6tjl2YMxmUsZdxvy8OzMhuldph7xcnGGjd4=,tag:Pp2NjUUAuXHu33q1CBlbnw==,type:str]
stringData:
    additional-scrape-configs.yaml: ENC[AES256_GCM,data:4x50myROfSrzTTV6EDQtcstA8mToJ/BROZZwj0ah8BqBymp/NjUJobPkeGoG8OV7Ug0sdUiRc1esea9NqHvlIGAX3uRVgEzydjsJD/cnUvSNRoGyPHs9mA6GKGhV4sHYWkTbwpx7cm6aSSiKm7gYb9RmeOmVO9YEoEq4TaokhLl+n3t3u6T6hun/k9ws+mlUM7ZrzLAZjISKyn4LpXoAHETCgDc6l/I6s62NT8fJSvqupvkyILlLeuZnPvCkjPJulakhyI5Xlf9RD2aMpmQ3XtkMropQpcGVuTe3XPoPZ0vx5DDK26rjwi8H5/XQl5wgxe7jCbP9UPFpqI1wMbw8eDuUexTUFc/eYZ+RyJzTkiOiG7lQJy8y2N400nQL2u2b72J/OpAjtCF700m9iic5+Amg0CsJPXQztOLXjuWB9FNfr/uTQ2uH1Pr+g3tr0hAZ/4sTfh14AstCJ/o4xJtBzv5dDg0otVZoGjx2f2Bp1EUToT5ZPcDPIkWrlv+TRQngjtueSesoM9S4Kar9lAL824GhI8m+8NSgMHg5E6kNXZFJYlPn4K19rsku5GCGDRnNneUOCayrGewX+pnJG7rrTPz58BDqw4oRLu1PI8ETKtv/HP+V/ZdGuFpWorpT+g==,iv:gVk8SfFUZt89qN1cmP28aS3ouVidMfI5djAHt/gwNwE=,tag:tg1+LxGtkl2wrlpGl38vzA==,type:str]
sops:
    age:
        - recipient: age139l36fqzkzsl9rs7n5wxn9yngs0mdt06taktet96gm7uk9gq9aqqxukvps
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIdzgyL2xNbEhkRkFRNmdr
            VjRsMFEvYS9FeEVrUzBNQjJNS3RoUk9mL1hNClFRMWdUYjdtK2FrdXFleUtSWXcw
            NWdONXRVS05hMnlQWEdPSkRVY0NibGMKLS0tIEk5ekcyZGhZNEQ5cTF1SzhNN29Y
            K0ZhLytQWFh5a1RmN0lrUFp2UWZ0R28KAAb6dVIIvMptDnuOAckF6FJhXumNOY02
            rYbnqnO6uP0AJCYRr4Q/alKNn/R/AVJdVB0puV6UetirQIB7xhFlsw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-16T03:27:52Z"
    mac: ENC[AES256_GCM,data:/TGixKj7RLjIo8M1pdQAsHEHupe5woq/HnO3I4nnx0ashYOuXxaz/9g5/JdSSF3VOvmuZ7LgfZLRjj4V/4dJahAcP5loDiTe1AxMlhJwU3fu29+k9CRQsmQeVp65U6+LmhcbgNK9vk/H9IPcDTaNDkXg4bxVeXYDLr0p9LpZckU=,iv:GVj7+wx7eybhhTbH/KsuYcA0cvy93bo5OvX4QkymfvQ=,tag:cAAhqwQv+gVvQHfzHv1elQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
