apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: mac-mini-node-exporter
  namespace: prometheus
  labels:
    release: prometheus
spec:
  staticConfigs:
    - labels:
        job: mac-mini-node-exporter
        instance: mac-mini
      targets:
        - 192.168.1.105:9100
  relabelings:
    - sourceLabels: [__address__]
      targetLabel: __address__
