apiVersion: ENC[AES256_GCM,data:hzg=,iv:HPbnClyOsIdDqKP5KKcQkFS4rBVqx5Bxic3AmpEGOio=,tag:lF4FQ+WLpujKXhiQq7yQHA==,type:str]
kind: ENC[AES256_GCM,data:w5OMfXgQ,iv:jnKiVKjpJ/R3embBWx3LJ3F8YEWi6eXFI1y7q6tWs0w=,tag:cOG428bi0UbN7cH3mnC1zg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:eMDp4JFnjapaqzX4ld0fTGU3RA==,iv:LOuVKv/6ebL7oK830HS9dNWTnMcOYy0bg3iKv1B1Bys=,tag:dUTReg/GumLy4teBApQZDA==,type:str]
    namespace: ENC[AES256_GCM,data:/kJ1OQIIAe+8,iv:9IqXNeYBzbRfFhf/RFIiT5j4g7Awy13TypecPZ7OKxs=,tag:PGfWsltuLosJJ7Qh2kbNSQ==,type:str]
type: ENC[AES256_GCM,data:Pv/XlsFK,iv:IQ3Hg1gipZx3u1+GMx5EGIG+sY36SSj1v0ju/8eKJHo=,tag:ulWB0bMdtN1na+HVKihQCQ==,type:str]
stringData:
    clientSecret: ENC[AES256_GCM,data:DFm1L0iMdRfVY5HX6WrugEaZ9eO337G3pyUHquCRT6xfAr9MlO8LAhRjtJM=,iv:xk6Du+QIfffLv7TysmehS+UOJkPQgiAQ9LinJUyX7f0=,tag:zR/9/6cJv+fSWz5gzkWvgw==,type:str]
sops:
    age:
        - recipient: age139l36fqzkzsl9rs7n5wxn9yngs0mdt06taktet96gm7uk9gq9aqqxukvps
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1ejIxUnlFMis0aEt6Zzhx
            dDZnTjl1TDk2bkIyN2FNU0ROS0QwdEw3VENnCnRJZkV6NnhlZXdTenplUmk5SjZF
            dFM0aVIwMTZneUNGOVpqeFVRc2pHYUUKLS0tIHVvQ0dERFFwV2Njd0pRTmVid1V5
            RkhSMjNoQTZGbFRsZ0p3MWF3UlE0Q1EK1aJ64Z40klQSGiHYK9jtFTQJ2NOHkCXy
            2M/+LAfBPSNR2VFGNOJlfd18bRs89JKHVxZVYnDqmzXtcAQ2vIo6EA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-26T00:15:16Z"
    mac: ENC[AES256_GCM,data:Djdmts3kKw2qM7WLAs7G+pMlmNO55e3X/QivM+1asCA1x7wvsmGkAeFZl2TIi3TYFYmKEbGlVtF6OIfzo4XI6pP/0V7jtEgQtqVRW21jfUyCrmKUMOYFnhvXd+o+p+X9FN6lxO9HzPrq6GtefBs8eli4ROMjElFoGjHpM8Sl378=,iv:aDSIrpdRwUWVJPxxmVVlz4n7H24r/+vdp8bqXmf2gtE=,tag:3TK5RizTRdMP7IRbcjsryA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
