apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: argocd-oauth-secret-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - argocd-oauth-secret.enc.yaml
