apiVersion: ENC[AES256_GCM,data:6fY=,iv:uzXqqGqgKLw5s6i/HKXi9KE5LnIi1rMuDxKTsrV8Mw4=,tag:85WV0Ya5IxQmQeEkLO3Rlw==,type:str]
kind: ENC[AES256_GCM,data:J6tCkYhF,iv:crp18Y4vYFVPgHq415fQgawE9SmUo6ycUCUoc4m/0/g=,tag:vSjBRRBtedp/nlza7CjWKg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:0wYHLQequFFPLlAI7tFZceOG4w==,iv:YKy93r+S1IR3gYl6LO7P1GmHiRat72knrg8WD+WslEE=,tag:4tfuwTt8jQG/hFd4guAh4A==,type:str]
    namespace: ENC[AES256_GCM,data:KS0nr52znyUL,iv:fmFqhD1KRj4eQiw/YkVVKBpP7R2B1MgPeRzl+5z5/Lc=,tag:r7kUveg+j6L9DCVbxumIYg==,type:str]
type: ENC[AES256_GCM,data:sXzTFTJl,iv:z+YcoEz//PaJ5h62H+K5lSlwsE5jYf3Q6SUjJ1lzt5E=,tag:28UaN7GajRXQzx4lnAaAKA==,type:str]
stringData:
    clientId: ENC[AES256_GCM,data:D2MtbXErf1Ops7V+mjcqebG2qgHJPQNNZ79TDqbjD55rY46mlZGyJULp+V4xYae0yq2B/hcEBwHEteifFZ2FfQj22OYlqdyD,iv:5CC8SvishOk51zq3PvYz10nX6rS3RzARn7JEve0rGhc=,tag:m40dfsvilc8F7HBkHq2EqQ==,type:str]
    clientSecret: ENC[AES256_GCM,data:nzXFJrtGNbK9gjIDaJTygncO6SyoqbbEJCdKq9o4v/dMeUA=,iv:CJL6Zt18mGFrb6m+wBi81mG8RcmorfaSdwXIxk4Kdvo=,tag:ukj+Od5s/Z1qHNcSgHOiag==,type:str]
sops:
    age:
        - recipient: age139l36fqzkzsl9rs7n5wxn9yngs0mdt06taktet96gm7uk9gq9aqqxukvps
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1NkpoZEFIL2tWNWdZODRL
            aWxaMDBqR1pqVzgxK3kramdKMTlhVnl4TEZ3Ci9zYVk4cVN1dHFPZEIvd0pqaGJm
            NHhTandHK2wwN3Niek5reVo2QXFTQXcKLS0tIEdNT3dVcDI4bnRoVkQ0UWVwcXlZ
            NDlPaUtGTjZPVHAweHB3TDdWanlmcDAKyvwjTgWf3h1kbw4q39uOLrLMXksNpATZ
            k8ofAVyx1g13QDsoAZk3Lg60DoCAM8AmrDXI713R/wE4x3yODHNC4g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-26T05:12:37Z"
    mac: ENC[AES256_GCM,data:z/lJHAKo7TKz9PrFNNM59MgkmYAEEIQkYxLVKyGPhEOAYWJ1wfgjcnEWoOD++4j9yFHGDweuoZbmKmXzTVVsDKryYWpi/naygLVFHWuDfUANASKDfwxL2+O55hYIN8oXGHqhyd+PIp9vR/y+aBp+L3qRZIAmHkQpIbw9G6gMGk0=,iv:1kUzDQLQcnvjCrzp06AUyLhgzSYn1Im3yh2GWsOQ2/I=,tag:evF05MJEXUhvrCoA7S8DEw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
