apiVersion: ENC[AES256_GCM,data:ONA=,iv:zJX6ugLNxFbccRq7G8vjMD9VVzJu8JI2Rd3MiQDEYKw=,tag:Ackrc1WEYDAI6mGwnNqu/Q==,type:str]
kind: ENC[AES256_GCM,data:2vZDhaUs,iv:klJQ71GUAkah0FM3/jW488ngPhyBHny/6R87HGjHg0g=,tag:sMHKDWCDLitu147tr8Py7w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:YVdp2gepfIHFl4h19fHSF/pPDio=,iv:TFQO2O9LZFD45xYTc8BWMf/pmjvKf3ZdAii9/SFNOVA=,tag:zJuItnkBjO3Ve0HWAO4FrQ==,type:str]
    namespace: ENC[AES256_GCM,data:dfJSvvTIjzS0,iv:+jZnDu5Gnrt8l/H5Z4YZ/gJ+YCyplVNQuhJmzWCCZYY=,tag:UZGIU7D5l3zOR7FPWsvubg==,type:str]
stringData:
    clientSecret: ENC[AES256_GCM,data:l1e/MKK/x/fnXuWzcSBUoAGT4UWTmvGYLG3J4hZpue8uOkbkgNDAJ+FirxxXs7k4XjjNkwWy,iv:kCS3SvCt4vGhV9o5PHaRxpKjWfoq1KWT320owz7CNQE=,tag:pc1ndv3OJKRjTc+pUvoxdA==,type:str]
sops:
    age:
        - recipient: age139l36fqzkzsl9rs7n5wxn9yngs0mdt06taktet96gm7uk9gq9aqqxukvps
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGZmxFS3NkMi8vejNNbFFS
            VitvM0tXTXBEc2dNVFhsQ3lVSkVUOFNreGhJCkdZSlR6MkJzQ08vdmNrTHh6MHpr
            STFVK3ZvZ3dmVWhTdm5sMkxMMUFSOGMKLS0tIC81MUF3Q2hlQi9HOHlFTDBxenpn
            ZVdPZTZnMnpUVnN0MTJ0UzVIaDdSYjAKjd+Vc8zchVNfR9dvM7z6HghsEar0nljD
            b3dJj71Wvx4y9uan93fGAWmd57JXjwQ54EwxpjS1HzCisCdNAerHQw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-07T23:36:42Z"
    mac: ENC[AES256_GCM,data:7T4kYAmm3abOYrz7bwwyiwwVgsmkA+zMymRZ60p5kJAkbwlrTF5PBVpDGA5PWYtWMz7rdfDFH4+TT4J6b/6vB8A4NpBl8RVxDtdIaQV0IA8NGL73dpBeQJ9Zjfo+CvM7th3n4T1Tbjze5wBoqQTnQtafJagh1Aq4Ijr/02n17KI=,iv:FkOxxdJpjhZTUEsfXOfaY3UUcpDkV54GKmj3ZttK/P4=,tag:usUtSnoreBaCKk2GWBUlEg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
