#ENC[AES256_GCM,data:/f+UYe3nfow8w0iZOmfM42eswUKs8/hzxoPqDpnJrBbPhO2uNtii6GV8WM8G+f+f,iv:pU0oqFsauUMb/HTA6fVbM0vLX/vKeb1B4bZ2oTV5EEM=,tag:GOauzY7+p0k+/M/JMNQpKA==,type:comment]
#ENC[AES256_GCM,data:EbKseG57bQ==,iv:Q3L8i8QNoNj87YuqWbny7JKI5D5tTr3zj/RZAKOxNLs=,tag:YNqp0oZ1HYqVH0ZC0XNqww==,type:comment]
#ENC[AES256_GCM,data:igxedfi+ksSH/I4yEaDSK3VsRsDHpxvJGxs5UqKBKHLzK7d4eC47fsWKLPmQa8GSAWB/UoQqmw==,iv:ePdsva8OLhFK9cAEzsm+VtztDY0ClnsSErLitDJYvPM=,tag:iUjG2nzCPuiAHeq7ybLjzg==,type:comment]
#ENC[AES256_GCM,data:62QSUelHUmEsyY+O/t+4vugL22Ec4dco8ddJscHUuUSmG8lg,iv:iSaYz5PGskhw9GTqjl9Cu8npvMqfYuVbbkp0h8a58/E=,tag:b9yKCJ9oKjCIdRQ1Gow2vw==,type:comment]
#ENC[AES256_GCM,data:dojyH4q4/c1rMf4dt2AxcbVksADdnyjrQtPW+YtV6MgdKNXVzLjUA6eA40K0dxOygPl1OYqV6eEZDETVcolZOE7XbunEskcgaCdtqc/gdkVDgjprHd0nx81UEIM=,iv:urLoOZuhTD5DioEWmik8BIJSaRs56ZvaXf0Zq/JGYvg=,tag:FYOwYLIOkqbH7Ck4nfj2Wg==,type:comment]
#ENC[AES256_GCM,data:eIzJ9a1V8jarissoNDuXTNFpBa4IZedCJVxdODtUFg==,iv:Q463li0vjzAWWkkij1dV3Y2GoB41tVzLG5DERAyKgXg=,tag:X7vBdNRMPYbA/xbdVRzi4Q==,type:comment]
#ENC[AES256_GCM,data:UscGVh5ncRuBE4V7ykn/NOBG8KXp1n0enP5+1P/AgYJ3egCFl0G70bN8Pn7h8uo/bLcF05JxUv3VztqeAs78LNgoslc+jHGIq9Ck+14s15NLrl585DcE,iv:mT/JQyIV53NCuJFpuK6vHm7mvUCUFY5B6hDK0+r87Xk=,tag:o7t49THIYHNDhEsTDt7rdw==,type:comment]
#ENC[AES256_GCM,data:493wG0xkwchbPBLrvgfGjtJ2kNNgTFtTv90Nxg2cRWLMpR0fMOD1UR875rWkAG2XsJNZlq/AnDoNTC24Dw==,iv:NnsanOw857riN+jEYQ1r/O/2v2w1SHbQuEHgTsckml0=,tag:i6OWm7w0VZxqci7ZiFlFug==,type:comment]
#ENC[AES256_GCM,data:EAVcPA4XN7/p0d9y1/zH5bA1iE3Wiv57Is4J2gkzAbB9gL4OA/PORwLYeGI=,iv:os+IY+jPjR7WcB4AyJP9G/9I83HCmtc2fYy+m2MB6es=,tag:C/Wf06Dn2PHbjKRhYy6SdA==,type:comment]
#ENC[AES256_GCM,data:B2COscl+E4xdzpMbXJzjUBEen5JU/cGogs4lPjSm3kH0rbvOoF11kZ9SDkrRAK4Ta49MLyF57RUfpO3z9UtZEXD7mQ==,iv:OHRU17fidJVNqm5mCQiwk37QsOTXRrReI6bly7CjNmo=,tag:qwH1tJY+YOVM8/tfKlsv8g==,type:comment]
apiVersion: ENC[AES256_GCM,data:xlM=,iv:aAe58wvRQJ1KLGn74OzFhYnZZ8PYcLup/E4ANWfdUNE=,tag:S+f2ShMLeGZpKIdUhuzRbQ==,type:str]
kind: ENC[AES256_GCM,data:mkrntl4l,iv:tGVzCYri3R28sMHTYESZKHzPeXnbLgDYWBMED6x8Dq0=,tag:Oe7Px9wiufNHBuVvgW+h3Q==,type:str]
metadata:
    name: ENC[AES256_GCM,data:OkHd8O7MVLb51D/7/e+QkKIZSrfHZGM=,iv:LNfkhM/2AweeJNc08fIm62CWmqH4je1u4LgS25r/32c=,tag:HQlFMf8D09UVmpRL6D8lqg==,type:str]
    namespace: ENC[AES256_GCM,data:o/9Y5Fb6KgN0,iv:qksU1XaxrE19CUbHVi6TYjW0MXM4JriNYNr99WZJE1w=,tag:UY+9mEbV1YkTsGaukidzjA==,type:str]
stringData:
    clientSecret: ENC[AES256_GCM,data:GLaUvsZ3+W7lg87gCEJK/5dTKMXln5O7jBAGoylSuwxZ5lnCKhN4edspv/eilRRXQZO/9Hcut703TTBsh7GgOA==,iv:+o+m+ks3cCX8VO3D9LR9xSN0OEHw1/Yy94k7sR9N94M=,tag:ZZJcbOXKtfjJho97ekoYww==,type:str]
sops:
    age:
        - recipient: age139l36fqzkzsl9rs7n5wxn9yngs0mdt06taktet96gm7uk9gq9aqqxukvps
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3NG1OYVlGOXFJUmdoSGJY
            dVZKdnc0RTdTMXRtRlp6aHJsaXdHUjRLSXlRCnhhLzNMajlDTGl0RC9hYVRtRTNm
            RzRWMVZOQndKOFpGdHhZa0NEenR5ZXMKLS0tIFI3N0VNY3hiQzR1a1I2cE1yd0Zh
            bWlOQXVNWjA2RExrQWNyTHhsQ2wyb0kKa0cdFZUYZYZvsZ5M55sYF1DbJcMXA3gg
            5OTAat8WpLMZbadWQNRuuncJi0FR/nkY0/pKuoUQ7fl13tQwuvpM6Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-09T01:09:07Z"
    mac: ENC[AES256_GCM,data:E6OO2MGA3EN2dAVwMAMqy7XsELbImyOGmYb7cecw5bfOBaK1JUA5a7sseIIqjRuRB0CA1ZShMcr38fJtS+oyclT6JmAHjUfPndqLfHLoA2L4EjoXUBxLVzg54I6yjx1SoolXrEaEM1FA951n0D5D8iIrOnT/+BL2eRxVgb9rT/c=,iv:LsQtrQ1PoKmaDvgn0fTokhkfX+7daPDUFZl4xh1ZT4Q=,tag:2OhKgpHSup7UDM147TiNWA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
