apiVersion: ENC[AES256_GCM,data:mwk=,iv:3kcLPi56sLJBbFXqS7IhtM9pUE2vv0yGq9+zQOUWtkw=,tag:Srn6jX+zw3i74lA1KFaHcg==,type:str]
kind: ENC[AES256_GCM,data:OTqPWRkR,iv:iZD856pZwOACiNm0OejNZnkQAya0Jw12ezIz0wE8At8=,tag:qiE1SqWSYzgQ6GOgHuwMHQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:tW2UIbgRfwzn75SM1Vmupcs=,iv:jgmaW+8S/6biPf5qQy+NdihHgo55+iYXHUot2aerWmk=,tag:m+VblllqtrFhVKWl1BXfsg==,type:str]
    namespace: ENC[AES256_GCM,data:gCy+lS0d3kMZ,iv:DRh6Cd8SztZksTLVj8W9D5xlj+jZrHx1U4bUZ+XnQi0=,tag:12CGgav85JVNR0Hiwl/wyA==,type:str]
type: ENC[AES256_GCM,data:qQkCSaxt,iv:a96bHMC7bu1MA/qbMinL8p2/2GGhDF487Yv83VSYxHA=,tag:bEOBJ74jveLbcIAhc0Zk+w==,type:str]
stringData:
    secret_key: ENC[AES256_GCM,data:ddyhe7dp5ECxVh8dQek3RdRu72zaLIRXIb3zm3FQVhofoUtu7mmyYT+j/bQOhKBFkNR75UWSblWhEO4ehx5prw==,iv:TLAVY2wmh8NpJnE4EJU4ziKhybH+LWbtGeoMFCHY9hY=,tag:5Dmq9jgOEuZkXRYC/YOs/g==,type:str]
    postgresql-password: ENC[AES256_GCM,data:7K2M5ytv6iKe/gN1pxaIL27wT7ejcliIZS3McoM4THs=,iv:D3qVWInznG/080VnzhxDz9npCTLNvVkb9fs/so3sUF4=,tag:QHcnuz01gu/doPqfQT2Nag==,type:str]
    redis-password: ENC[AES256_GCM,data:cCw3eSzEBIT56SXiM3qOeYZLVTtJAdNG5pR/wrR6PUk=,iv:+f8QVjlPPvjWB71Ba5yIt9H7ZBpDMl4ZDO3o0tD0AE4=,tag:FLrkCHR1eEUYSY5ijxlN2w==,type:str]
sops:
    age:
        - recipient: age139l36fqzkzsl9rs7n5wxn9yngs0mdt06taktet96gm7uk9gq9aqqxukvps
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4Z24vUzVvTi9oNS9RTmpZ
            YmgyK21tTnB0NGVkQlZRR281bFhHREp5VlgwCjRRVE1tdDUzRTJ5ODlISmhzN2M1
            R25rbk9VYXdwYlIxWlNhdFZNWHdaM1EKLS0tIGVjaCs3RmFjQVhWdG9CVm1JWDZ4
            SEF5cnRvQVg3dDFOSWJ1WkhsOWpYK28K2GOWU/PCfiB0c5i5Wnj8Vgx9P4+dYVmN
            kYoAqaG/eFFbCUdGRjFbhTwb/JLmrPZHRLvSQ/e0dkBmyvgwpGpaUg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-23T05:11:42Z"
    mac: ENC[AES256_GCM,data:9Nj69SVliugPGG+HhkzNfRvGzr5X5scUpENKXuR0rle1NMqHkYrbbcD3mhLHt0IU5B/e2e1iPOnNsjJ/702b5WieepEZUeKs1MNXXel76nyAWZvm7I3mi63NPCkPZ/Z9rPTJkMitSpFt2Hlh5c32Iz0EnLsepLm3QKGK7+VWZNE=,iv:roV9iDNVxRhshu5lv5QkycE+oalA5Bj4aspZB7KHbbo=,tag:ATc3qkzCveKZMTe30y3gMQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
