authentik:
    secret_key:
        existingSecret: authentik-secrets
        existingSecretKey: secret_key
    # This sends anonymous usage-data, stack traces on errors and
    # performance data to sentry.io, and is fully opt-in
    error_reporting:
        enabled: false
    postgresql:
        password:
            existingSecret: authentik-secrets
            existingSecretKey: postgresql-password

server:
    ingress:
        # Specify kubernetes ingress controller class name
        ingressClassName: nginx
        enabled: true
        hosts:
            - authentik.homelab

postgresql:
    enabled: true
    primary:
        persistence:
            enabled: true
            storageClass: local-ssd-storage
    auth:
        existingSecret: authentik-secrets
        secretKeys:
            adminPasswordKey: postgresql-password
            userPasswordKey: postgresql-password
redis:
    enabled: true
    auth:
        enabled: true
        existingSecret: authentik-secrets
        existingSecretPasswordKey: redis-password