apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: homepage-config-secrets
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
  annotations:
    kubernetes.io/service-account.name: homepage
data: # TODO: Change to sealed secrets later. These are all just default passwords and only locally accessible
  HOMEPAGE_VAR_ADGUARD_USERNAME: YW5vcnVt
  HOMEPAGE_VAR_ADGUARD_PASSWORD: YWRndWFyZA==
  HOMEPAGE_VAR_GRAFANA_USERNAME: YWRtaW4K
  HOMEPAGE_VAR_GRAFANA_PASSWORD: cHJvbS1vcGVyYXRvcgo=
  HOMEPAGE_VAR_ARGOCD_KEY: ZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SnBjM01pT2lKaGNtZHZZMlFpTENKemRXSWlPaUp5WldGa2IyNXNlVHBoY0dsTFpYa2lMQ0p1WW1ZaU9qRTNNelU0TkRRM09EQXNJbWxoZENJNk1UY3pOVGcwTkRjNE1Dd2lhblJwSWpvaVlXSTJNVGcxWXpndE1qWXlZaTAwTWpka0xUZzVZek10TURnd1pEZzRNalF3WlRJMUluMC5zeXpRRHFoOVo3V2llUjAzZl8xN29aeVR4c1otQTd6TnNweUE0eTJtaHYwCg==
