apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: homepage-config-secrets
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
  annotations:
    kubernetes.io/service-account.name: homepage
data: # TODO: Change to sealed secrets later. These are all just default passwords and only locally accessible
  HOMEPAGE_VAR_ADGUARD_USERNAME: YW5vcnVt
  HOMEPAGE_VAR_ADGUARD_PASSWORD: YWRndWFyZA==
  HOMEPAGE_VAR_GRAFANA_USERNAME: YWRtaW4K
  HOMEPAGE_VAR_GRAFANA_PASSWORD: cHJvbS1vcGVyYXRvcgo=
  HOMEPAGE_VAR_ARGOCD_USERNAME: YWRtaW4K
  HOMEPAGE_VAR_ARGOCD_PASSWORD: YWRtaW5hcmdvY2QK
