apiVersion: ENC[AES256_GCM,data:yYM=,iv:NHWc0MmkgHwok/D3y7fyBnAZDf8gIvyQ2hft803xeL0=,tag:0vUVz5JV/UqQApRVsGytfw==,type:str]
kind: ENC[AES256_GCM,data:9YDGRxc3,iv:jVEoD1zXV5LdHum75s3xnxxraVQI7MPKvAcbF3Z9AIQ=,tag:WirCoH0ikwW1fgQ+5Juyaw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:qtiHlc+D2l1YO8kTf5t682Qji6OCeo8=,iv:mQwmLRvYJTixwY/uRhZ5xjCprl/ihMaSOm9Ko8sc3vw=,tag:QIM/kjBtCjq+qx20NHdYhQ==,type:str]
    namespace: ENC[AES256_GCM,data:yhfWn0Gga0M=,iv:MhrAeZIrX0orqtEXvacXu9F+CYKM9bx/F2vi6+d6eac=,tag:52Kv8egfHT8jLuLcLsqpnA==,type:str]
    labels:
        app.kubernetes.io/name: ENC[AES256_GCM,data:XihqjlvEgng=,iv:Kb3ldsWNwTB2Xi89JvItpFyCRxWGJ2IXH7b8+bdyHck=,tag:MsLujznwz2U2yqRSaaHvzQ==,type:str]
type: ENC[AES256_GCM,data:u/xGAlso,iv:4hCXDHJZETk4NSLA5AqdCESIvFzUcwHPIfcnHuBI7FY=,tag:HMgzvKc/pmd/L1Ncjk0urw==,type:str]
stringData:
    HOMEPAGE_VAR_ARGOCD_KEY: ENC[AES256_GCM,data:LlkMKNBSqdbKiRpaIDrhjuqZjaXhFLO+8UnCQsICzi4UqxCAONnVcn+UW33XBJtjrvAR13ZWQ+8rOON0cUAkDcNdMPit+n2ZpWVkx1V6T38M1WBDmuaMc2yoK85GrCSmDror52I7GNzZNcAl2xATWXWTq8oanHl+JDo9XwvWwEpscwdg2DGwsTJbdSXmUXgy+yqvcxvxoifo5ELxFV0mNVLnAja/BoEXcd8PVQkG0GxeDOa6i9kCogl5vsZ91KN84UvjFwgXv0STvvd879QwOzHZb1b2RzDen4ZOB/KD8ADNx9+5sJMUW9wQ/ynu+nie,iv:EbGbBKNLT9KAiRwFSrurYwjbfOLzv9sKYrph9/uhF/Y=,tag:gLESll1NzNypCFdK6KOhKA==,type:str]
    HOMEPAGE_VAR_ADGUARD_USERNAME: ENC[AES256_GCM,data:wJkWsU97,iv:pd63OQMSe7L2xlSBr0TDbSn4CATbAr7u5BPumRQuotA=,tag:aLsCDlFLPmOB7o/OPeTmsg==,type:str]
    HOMEPAGE_VAR_ADGUARD_PASSWORD: ENC[AES256_GCM,data:5LLC7Z3lMv0sWTo=,iv:PGbVYysdlTVJjV8kwTdlAomtlz3SNQj6671KcJXJjLs=,tag:yRnFMU5yHy+NPdPandV8Dg==,type:str]
    HOMEPAGE_VAR_GRAFANA_USERNAME: ENC[AES256_GCM,data:RQ3tnk0=,iv:8B9mzW69Txu9vxHOlcD0qMSKb0xbnwBYC3yGYIaxHy0=,tag:va3i6DkvhOyy1S17CEWazg==,type:str]
    HOMEPAGE_VAR_GRAFANA_PASSWORD: ENC[AES256_GCM,data:Jz/QPxP5aHeWuAlz61B98r3tB87OFdYHlaj9fwjM4jTUmkQHUAWYIw==,iv:LAW+Mdaf+yhh9MMGZZi+vU7+4KTV5nLJkSh6Iva4vz8=,tag:pTo7GOhAe9lCq9UWsWteEQ==,type:str]
sops:
    age:
        - recipient: age139l36fqzkzsl9rs7n5wxn9yngs0mdt06taktet96gm7uk9gq9aqqxukvps
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCVlBRYldQNkl4NGxweUFs
            Zi9mOXUvNDBqNUg5eU9tTjJYRXlyUFkzQ0RnCkNseUdDaHA3S3RIWFlGdFF0dFM4
            R2t3QU9VYy9Kc2E1RG94c3BzZ2tiU2MKLS0tIGc0Uk9sbFR5VzJIdUU4by84Z0JH
            Q0dDUmVBK0IyR1kwTUtYK2UwVWl2ZnMK1lQdnDi66kauCsx+khEyC661Js0XscWC
            L+5wxd2PHsAsnyVnS4/N9mZS8f8exfGEdlAFZ2RIzkp3HGIRbt8dHw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-09T18:07:53Z"
    mac: ENC[AES256_GCM,data:mo2XER/TtE8pDqHjz4eIHfyj8fzsW12DaugA3jaQoopXMqOZb4v6vOKoBKT0AMFXzzEa1exkV25eAhxZJlgXs+cB0N+OCdTYBmKI5aQ4Kq63OOliuDjgzLw/+wzrkq2x96+DL+Waz3lJHsWwvx36mDUgsPsY1e0ek2MM+56Fako=,iv:JiUL2Ee7LGR7n1s/qeYqEeZitgp6Nzr/kzHZM0J2bnQ=,tag:cTP7XcmbmkoJcaD3ozzuTQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
