apiVersion: ENC[AES256_GCM,data:yYM=,iv:NHWc0MmkgHwok/D3y7fyBnAZDf8gIvyQ2hft803xeL0=,tag:0vUVz5JV/UqQApRVsGytfw==,type:str]
kind: ENC[AES256_GCM,data:9YDGRxc3,iv:jVEoD1zXV5LdHum75s3xnxxraVQI7MPKvAcbF3Z9AIQ=,tag:WirCoH0ikwW1fgQ+5Juyaw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:qtiHlc+D2l1YO8kTf5t682Qji6OCeo8=,iv:mQwmLRvYJTixwY/uRhZ5xjCprl/ihMaSOm9Ko8sc3vw=,tag:QIM/kjBtCjq+qx20NHdYhQ==,type:str]
    namespace: ENC[AES256_GCM,data:yhfWn0Gga0M=,iv:MhrAeZIrX0orqtEXvacXu9F+CYKM9bx/F2vi6+d6eac=,tag:52Kv8egfHT8jLuLcLsqpnA==,type:str]
    labels:
        app.kubernetes.io/name: ENC[AES256_GCM,data:XihqjlvEgng=,iv:Kb3ldsWNwTB2Xi89JvItpFyCRxWGJ2IXH7b8+bdyHck=,tag:MsLujznwz2U2yqRSaaHvzQ==,type:str]
type: ENC[AES256_GCM,data:u/xGAlso,iv:4hCXDHJZETk4NSLA5AqdCESIvFzUcwHPIfcnHuBI7FY=,tag:HMgzvKc/pmd/L1Ncjk0urw==,type:str]
stringData:
    HOMEPAGE_VAR_ARGOCD_KEY: ENC[AES256_GCM,data:sSo5eJNN1lcvvbBkJ+jFn29jI8on6gA9iOLpCHRAxIepnO8=,iv:G3hcsgB3etR/OsoXCk01EtWBhILSLvyypqpRkwStJOs=,tag:TaeSu1blHn5RsB/s4HJKCw==,type:str]
    HOMEPAGE_VAR_ADGUARD_USERNAME: ENC[AES256_GCM,data:iCnJCKDL3wEv6s0=,iv:AWXu9zF7WgntwjP4xqJiQODTh7HQtB4Quf3FqkSjQIs=,tag:CSvSGrMWAW35Jwj1f4daPg==,type:str]
    HOMEPAGE_VAR_ADGUARD_PASSWORD: ENC[AES256_GCM,data:5LLC7Z3lMv0sWTo=,iv:PGbVYysdlTVJjV8kwTdlAomtlz3SNQj6671KcJXJjLs=,tag:yRnFMU5yHy+NPdPandV8Dg==,type:str]
    HOMEPAGE_VAR_GRAFANA_USERNAME: ENC[AES256_GCM,data:RQ3tnk0=,iv:8B9mzW69Txu9vxHOlcD0qMSKb0xbnwBYC3yGYIaxHy0=,tag:va3i6DkvhOyy1S17CEWazg==,type:str]
    HOMEPAGE_VAR_GRAFANA_PASSWORD: ENC[AES256_GCM,data:CXruX6HmEuigheFuk+EevwJfjloO6BDOf4QL7aSfcm8VX1/b,iv:3CTSjbAyiBD/wQL33wfLh9+Uqgbo9Lr297O25YAm3BU=,tag:PXQS8iDACj+zXp8Jc/wEaA==,type:str]
sops:
    age:
        - recipient: age139l36fqzkzsl9rs7n5wxn9yngs0mdt06taktet96gm7uk9gq9aqqxukvps
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCVlBRYldQNkl4NGxweUFs
            Zi9mOXUvNDBqNUg5eU9tTjJYRXlyUFkzQ0RnCkNseUdDaHA3S3RIWFlGdFF0dFM4
            R2t3QU9VYy9Kc2E1RG94c3BzZ2tiU2MKLS0tIGc0Uk9sbFR5VzJIdUU4by84Z0JH
            Q0dDUmVBK0IyR1kwTUtYK2UwVWl2ZnMK1lQdnDi66kauCsx+khEyC661Js0XscWC
            L+5wxd2PHsAsnyVnS4/N9mZS8f8exfGEdlAFZ2RIzkp3HGIRbt8dHw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-23T05:11:55Z"
    mac: ENC[AES256_GCM,data:HlR/eeWcplFlxlv3DzwF+U1tKhbR/a6FiJkaB6jVLU0Xfr4caBDlt7AKSOEq5w2WeqQl21hKFozUgJPJWcEDwS/QzFuyEQ4rt/l1Rr6JwMyAQO926508eBW5pt8vbtGS2AGGwOVnCG8Pd18g0RJZ2/y86etOBy2W/CAQzAyeBlQ=,iv:x5TLR4vojdmHjBfEilAvp/6dD233xKDK9wwf1CFiAF0=,tag:uHRNSGNMNuEmJAXZOTASnw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
