#ENC[AES256_GCM,data:MEl5PYH1EMVjagFvIHdasPMf1p++wd7bytJzGpP1nix7QGBXNCWbdHhclFYI0npr,iv:UbYTMPTKdlBVFcCZTMH6+mnwdW6vVUg9lN4EmKFS7TQ=,tag:UEbWHwfZEGD2bKDJd5AnVQ==,type:comment]
#ENC[AES256_GCM,data:U5RoPJN+9bken+sXf0hMK45pFa9kjcQGp585650l8K7X68R5fdfcv1Dkq7jGpx5EGyrpPAiMkEBOcjLIE7bAz8Be1LWsV8ga,iv:hQoxG1Sd9Cm51kdkiI08roovTH0EyNlVvFwl2J10SK0=,tag:0t/hCg2gWDG2MZ14l+MCcw==,type:comment]
#
#ENC[AES256_GCM,data:0Gcn+98Plw==,iv:J4/D/Fqz9qjA9gOYdirMuo3gIagQdW7HpAU8HTUj+oI=,tag:HlzkIpn3GU2vLDBc/HwyDg==,type:comment]
#ENC[AES256_GCM,data:MSj/7r3SUGBzNuA/icrZMPfFGfxOqTWjyDzPgaZE8NG3,iv:cNc61htvhk1LlLOu3HA4XwX5IKlH2gPkVg3mAfQmTJQ=,tag:0hg3za+4XBwLi7HuOoAiQQ==,type:comment]
#ENC[AES256_GCM,data:0mZN698AziN2zxiyMeJFd7yEoqG/dtfX+53ONnRj7Gytu+c=,iv:ufNPJfVTvpXA79q4YwvSxVaVujF0k1F5z/MOzcJ6Ndk=,tag:LdVWmXkXz2rwZgtrZkZZNw==,type:comment]
#ENC[AES256_GCM,data:xAM0zrb6DaCgA51dOXOqLnnmbk2Hdrs48MWaSEsMfdpIPAwm/L6FocSsX3Ux7dkP57ekPUGM//KFPAsfn08BSmGzOzoiKw==,iv:HJH/gYBjakUfI/IFDVX/nsdWmmh6UPNT2605eottcJo=,tag:0M2RCyytq3Vmy3Vq5W5TDw==,type:comment]
#ENC[AES256_GCM,data:ZFqiazZtFe/LSe0jytoGR61J8I9nq+Q/QVQ=,iv:7PoqjajyNS/PrdPAX4DqMVH8DNjb4Y2/An/qiGgd4Q4=,tag:GKGOoomNya54Acb6PcL+mw==,type:comment]
#ENC[AES256_GCM,data:Q3GHu+xQ2cUenavfoT/1zOQ6SohxqkuM0pixjV555ShuzoLjmqUGFSB9ABr1JTd/Lx8O33w9RkJnDnRWjFA1bvY=,iv:iJe8oGPQit1yYedu5UX2RIk6ErhsmCyHxbKL0wWdi9I=,tag:+kSZtjsdWsCmoWg6KnaLNw==,type:comment]
#ENC[AES256_GCM,data:gmwR4sVp3Xr7Ja8nXHaOXXZFWtRU2HFYlcu28hKoMqfB7LHfr0nds4R7m2oZWg==,iv:bQksjp37+/wWBb7cK477Tja5qbccwE2E36wxAMG11pw=,tag:0U9QdV5Mb6DeOf06y+mWaw==,type:comment]
#ENC[AES256_GCM,data:DtECwlqz67kKjxrrCbXVam7BDU8t9xY275kk181Jook=,iv:+Liod6C98ickgyxXnBrVgheThkcLIA18aF9VP1fUs/Y=,tag:nYlAnN0l9Td0zz3Z0r/UUg==,type:comment]
apiVersion: ENC[AES256_GCM,data:nUo=,iv:wMqnH4oV9Jn5Tw6i86WDBkCpFgfr+z/0lVs7o2AcY74=,tag:utjkyKBqrSpNN1+h9Me6Hg==,type:str]
kind: ENC[AES256_GCM,data:woPjJN+l,iv:RtivCihtV64qIi/lallZksdLw859WHpcmWj67C20kVg=,tag:3cTOASuJg4KpkGeM0WKDrA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:JNeXvRxCZagxV1s4sFqLBA==,iv:lItWIyc+vhVVpqCF/8icD8Dtp7ti7jNJ1pMck4YGdPw=,tag:RbbkhVwZ0JXUU33vttF4vw==,type:str]
    namespace: ENC[AES256_GCM,data:ULwTyGdIxpAuew==,iv:2DRziRXUFjmkoZj/yW4lOu60Ss/Q6+kG+WmIZrg7Xmk=,tag:aiRI5dYdaTX0vXsLOMXARA==,type:str]
stringData:
    OAUTH_CLIENT_ID: ENC[AES256_GCM,data:dKwTd4odsus/FQ==,iv:kcAr98fpGprMK0hyIXPHCR+YrsMBe+UUz7bFQ/6OKJ4=,tag:pyqKh9hJMKrXbEwZOhgF4Q==,type:str]
    OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:u+cz5Gjs1lRFAKkM4alRtBGKAxYVkx0mJQlqNUo0LXbigXUL2mbSM/Kc01Rkte5IdE2kuPQxR8WQ0TAi6jbYGg==,iv:s8uJn1R3yvMTdDaP8qoDtGlKlNgYTophB9GKmhjvRLE=,tag:/3AejZ+Yxmvb5gFjhlhq0Q==,type:str]
sops:
    age:
        - recipient: age139l36fqzkzsl9rs7n5wxn9yngs0mdt06taktet96gm7uk9gq9aqqxukvps
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDUEFnc3lROEtVdUNSVlpu
            REhUTlV1SlJEUWRFYlh4QWRITHp2dzFnWXhBCkQ4VW85ZDV2Nm5hT0JnVDJ2c1RN
            VDJzNlova2JaQ0ZuTXpibGx4TmNCak0KLS0tIDJjaFllQlRWMWNZU1JrazJQMXVQ
            d0VHOTNOWUJVc3FKTkpNU2ljNzRHZm8KgZwi3jBw8HKqdc5KiAwqPu0sf0pcLlUp
            40pGvlIA8XBSXQyKkrlML4L5BOkb6yiZ0yltl2eeTf5SxmhoZ+l9nw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-09T01:09:07Z"
    mac: ENC[AES256_GCM,data:6WJWi1sBQqLRNJQUBAw2T0/jtjnpm9evO/RPsuOt9IOo/GfyRpsKs+dtlwlr+U+qaLD0vMIiduQS7lWRVvn+xxQN1BGuejnyNoO8AqSWAaKzQACRrgnaJ02D3wUn+U1FI1eGhjsrL8ZVoXgZFyHFx4b81vZAYbDcjtg5LpUeJZA=,iv:u4HK/yMRcBeRZpJH7dNMXQdaHORiK+DIFENEALU9hQg=,tag:XXyKKSkEt+/yK3YGTFLmsw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
