apiVersion: apps/v1
kind: Deployment
metadata:
  name: adguard-deployment
  namespace: adguard
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
  selector:
    matchLabels:
      app: adguard
  template:
    metadata:
      labels:
        app: adguard
    spec:
      initContainers:
      - name: init-config
        image: alpine
        imagePullPolicy: IfNotPresent
        command:
          - 'sh'
          - '-c'
          - |
            cp /tmp/config/AdGuardHome.yaml /opt/adguardhome/conf/AdGuardHome.yaml
        volumeMounts:
        - name: adguard-config
          mountPath: /tmp/config
        - name: adguard-conf
          mountPath: /opt/adguardhome/conf
      containers:
      - name: adguard-home
        image: adguard/adguardhome:v0.107.55
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "1Gi"
            cpu: "300m"
        ports:
        - containerPort: 53 #dns
          name: dns
          protocol: UDP
        - containerPort: 3000 #initial setup
          name: http-initial
        - containerPort: 80 #web gui
          name: http
          protocol: TCP
        volumeMounts:
        - name: adguard-data
          mountPath: /opt/adguardhome/work
        - name: adguard-conf
          mountPath: /opt/adguardhome/conf
      volumes:
      - name: adguard-data
        persistentVolumeClaim:
          claimName: adguard-pvc
      - name: adguard-config
        configMap:
          name: adguard-config
      - name: adguard-conf
        emptyDir: {}
