apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: adguard

resources:
  - namespace.yaml
  - configmap.yaml
  - deployment.yaml
  - httproute.yaml
  - service.yaml
  - pvc.yaml

labels:
- pairs:
    app.kubernetes.io/name: adguard
    app.kubernetes.io/instance: adguard
