---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflared-token
  namespace: cloudflared
spec:
  encryptedData:
    token: AgBUkYegqXqMEAIveSzo3Y9rUwlXdmWBidmvN0If4W+YN7e1yOrQXhlh/JSg/RrF6daeH//0U2A103Q6yvd7/Ld2OLuTsmb/8KNydI6M+Uf5w4g+VAlClMIcavG/6w29cMC7wUZMINjkZu7+pzoupHAigf9oYhOOasrQ3cR2B4paxyqwuH/A50eVnnwQkHIbQ1JI6eZQvUWlNsANDaLWXszmfhRb2crdHhBvdr8h66qvg9WI82+jbslsaIprgLaOxwfS/zx9kgEnS1qQjAwJy6P4muk0xWqQ5lhWwIN8Ualiq/twbQqjyvbXgwW+VV0CzkUaj4l22WHbyxgkdnJKcQJlPiTa7UKIGy7witWD7HktET45RH3j/CjZP4TxUjfPRYH3u7Yf+pmvylJC6VDpUoKa1DTbX8EGIEvHH1nCQtZcFSkIgx6yQ/a5ojXR3vnHmI8sW9Cdz085XXnJdsHf9J5JBxv1kFO1mR9cqb0t6rgeA3L1sYvOj5AHXrrQCiiP2mUWrlcnzi8rldH7arKcWrUxv3qCyupKa5s+aa2xxqdbn+7ARfj6X5iFe0Vd8GjGqMWilaWiHhaogjoqvaf2+cEYVSzHegLq9QLvQqj94w7A0urfmbRTNyUKflHe26xJ+2TxeyUT7SRfNTsb9V66HOzLiDPi8I6SJ/kLMrI1yQ+d+KTVKVu2szCDH3ilUriTXK2W33KlNXD1OpHCVQTHYri24WTEsvG4dPFcsHIuSMiPCC0YUt3wh/CKe4fJqTDL1Clg4anCJ6K7BA==
  template:
    metadata:
      creationTimestamp: null
      name: cloudflared-token
      namespace: cloudflared
    type: Opaque
