---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflared-token
  namespace: cloudflared
spec:
  encryptedData:
    token: AgBxTnrF6mtnV1O+BDh19a0bkkko6MccN4cTTxHhtXcOwbByNOgNh5zbkvOaWSdS9mznZEH2Jup5w7ineLRhMIiPlhxNRxVZvt1Att4qHRRurnFxhOYBMmrq26+sjdeVQtqx59N583ZpgpmeHey/8k8ccqgMrQdttwMT5gMOKVEdfRNrnir4xmF2A5Gb56ctYx2vASSnoy4j2adRCOPcwyt2d8R3M+U2AA2eYg1CdgI6POoqwrcIRHowA+nA4fiNaP0Y01I76tFD7AssVDI2CRcxYAOkbhYjzNdROMnKDdjcuFDtsMmFfUV+/Mxy1J7OcmdyrA8qAXbZ7yRs1CTraDB4VIKy7JTMrIfHP/jT6MAxUwp7hgsd0FeYGtGze2XRMITm+G7Xk1a91pB7Tm9HSPpodyPvYDWkLcd7bCVUpstoX7ixHWpduPH1tifS1ghKQW5jMajt8HhhbpipKVWvfMTcZMoHf9Po2BBRD+UNFspy0ersx3IXFU1EOLWfeYsD3fbE+7rIy/gSK5UEvBMqgkG2pRRxNCW66fInzs9rhgKLeQaIzGA3Mgkjrg6uBdKijid4RC6pHkPFiM2rdBJ40WjOOfLY9bFosLengmxI+a3dOxhLuiRUiSSIx8dhnsbjctvMVVHpHb3uGYIesQXerKD9MzNkW4holtaMKNOF/nyZjvoqIDHurp2kx7LDEB9Vs2xTWrkQHDNDCTDllU/mtkvDvKiGXluVR+q33xdBgLGD5V76ch/LDhkOUUFxqQjit/Cn5+65InWnDqci3D7bqyZ+67+sJan/GB7uhkMzZaotIoYX2ZCJyZL/X8XOmnDeRh8QlgKkAq0hVv0/Kog95FFTmHbbIFEaUwK8vVDCm9/VoJA8luXssyrNgkk=
  template:
    metadata:
      creationTimestamp: null
      name: cloudflared-token
      namespace: cloudflared
    type: Opaque
