---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflared-token
  namespace: cloudflared
spec:
  encryptedData:
    token: AgAA32lkj0i+blLiphOO5RXb58iXQ33Zj++xMWCvJEU/ifcjhMGl6pMyI0mckegf3tbSGw6x9RBmw16CkfCRZwNf9Vy3rDQ8jKELLssXW87tViPVZvbK8a9qv6XNSwy/M/Vo8U7WNT8vUxE514PXiO/SyW+bzGpVcHZNoHyCd3//Z2Or9E80EBVLBhyww0/xXrYSTR0gbC/owqg7yLhtTj4ecHXmWdi4EXwA1dLUEmiYY3uUhR20FuUdFVgTOnDJXV/fkmD9+8Wq5P7hCYG6hLo7KhW6voU1WeJ0MuZww9xOVnyfOzFr5PT61DKWI4W6EcnzLTCV902tYDBrlkBy0IiK2GUlQQKqDCQqJmtJRdg93uZJ+3q05bCuvUKU9wteApkTi8CefJbD0+nUJZkOjMeEQBChNdnparTQxy1QdnmtarclD/RDmb5oFXwxkaOpEQRMx1VKMDOmEI2iarTVDImDa5a3v/FuRavSJK8i5ix7MBS75vjYtX3ZpnXBzxezJ6+IQtX5iDt7Gw8f4Ujzcp1+XVVXZW2/NTDSQw/syng2aBHzR5IFFwkxff3js4ma6JsEwqCYRngiHAm0JtaSAKOtvGLdkEh98pHWxOjiN9EAVq14XrF/nkBJHHNyfcB9eKhLP+3UQby/npz8hqiq/dKGjBB5BH+GvVhWP9Eo0PDCh86vB2KUGpSkbAaWzCqQDpSrfrJV7gkLmfNstHF/9OpEWI6IbcLOW+4wyK+Qm7o8xlEYbp7ExWJjaxvt+j4HlHv31qxAvWt1Ug==
  template:
    metadata:
      creationTimestamp: null
      name: cloudflared-token
      namespace: cloudflared
    type: Opaque
