apiVersion: ENC[AES256_GCM,data:G1I=,iv:eBuNt/RlTVj541M1FvBWLuKV6jjGMHZcDHyLcPlJF2Q=,tag:xqUQFWAEbXky9IA6brdq2A==,type:str]
kind: ENC[AES256_GCM,data:g4lluDV/,iv:6ZC3NxvKRAzunvQFj1AsmRnGvdMciObFzmQGXL/eYDY=,tag:WC8bfYxMtGwS40YqrrI+yg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:w6FHr1lWy1F0LqsDhn0+TNo=,iv:O9JRT+AN+H9lWxtGnZfrOFQDfaXYcdfoqaPXyRc+v9I=,tag:YtVG4Sh63OJCSGyUJFKY7A==,type:str]
    namespace: ENC[AES256_GCM,data:AqEvBhAf6BKe+as=,iv:9mcr0vB0E9aKTWETB86f47ykbn+b9R2zuFNGDy+Ve3s=,tag:pYJEgGv6fI7aYeaxh5e9Mw==,type:str]
type: ENC[AES256_GCM,data:uh2pgd8/,iv:oRit6ANo4R52GNOleOeXf9YSNC8VCQfVgDT+ZZ8DIBg=,tag:cCEavlI0KHQUiAAWtsz3SQ==,type:str]
stringData:
    token: ENC[AES256_GCM,data:NSAi16G/1IANS1Vy2tlQMXP7pOsWiYtCaPgYGjiKAsNZGWI1p5HJwaWmWbMPFJm9bkoJAT0l0ucytCqNZ5j5/T5JuqSHbQxueBGt/m81V+y7ojmZ5nQfbnSUZkrN6hf2DBndS2ubgvSwsssF5AnxHz62Fg6D1HQs952Re+ekj/hn+T1c60Klm4EtcjMxAYaOxpduADjBYMw+HrEQCGtMkIg0f49BX4JTfiuHua6QgqfjxjLCI+VYhg==,iv:lwfyUX0Ep3eSbA8aQDp20BRNXCd5qsDaMItTs9UzxW4=,tag:ys2HwXe1JHw1HknSpVIrfQ==,type:str]
sops:
    age:
        - recipient: age139l36fqzkzsl9rs7n5wxn9yngs0mdt06taktet96gm7uk9gq9aqqxukvps
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3Vk9qQ2djVFQzTUVxeFpO
            NzVTVTViYmRCZGhMbjVoS0JZRHNTUDBOdFZNCkNIcmJSYjNBU0VRWG1IbnFYUktV
            dFNwRzAvVStOank3eUg0SHhpWWtNSDAKLS0tIG90QnJIREt0VE1BSGg2VDV6Szcy
            ZWJ4WndJQStpM1hualdtWkRLdXhMN0EKGqZYftksvibqhiwYSbw/2udFW9tSmS57
            UVgxF5cwos2dj5Pjbs/JM2eQhrHOP/1LEZVpq7Qs95uDLib9pTsBaA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-23T05:11:42Z"
    mac: ENC[AES256_GCM,data:GJDNIMTZqwT1Tms1gqhHCqLkaOvL1dV6prtbs8leOK7V945YUHUqV7WDsR8gN7JUnFWBzyrNz09x29OhEhdM2xCBpuRfIYO3q9JT2KMKcW5S5DIGcW77WxMCyN9zfbhWHmGMGEWAqiXZt9Sv0kKGrI3jPDnzlOZtI6XUvIn/mBw=,iv:DT0W2lqw4JIzBBRAZiU+DaLAD69DDhDWGzXBFap5vFU=,tag:YNgAgvL6r8jt7RiqL1Kl/w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
