# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket       = "anorum-homelab"
    encrypt      = true
    key          = "terraform/homelab/terraform.tfstate"
    region       = "us-west-2"
    use_lockfile = false
  }
}
