nameOverride: ""
fullnameOverride: ""
config:
  metrics:
    statsd_datadog_enabled: false
    statsd_port: 8125

postgresql:
  ## to use the external db, the embedded one must be disabled
  enabled: true
statsd:
  enabled: false

### ENVIRONMENT VARIABLES
env:
  - name: "AIRFLOW_ENV"
    value: STG
  - name: "AIRFLOW__SCHEDULER__SCHEDULER_ZOMBIE_TASK_THRESHOLD"
    value: "1800"
  - name: "AIRFLOW__WEBSERVER__NAVBAR_COLOR"
    value: "#f514c4 !important"

### DAGS ###
dags:
  persistence:
    enabled: false


### JOBS ####

createUserJob:
  nodeSelector:
    kubernetes.io/os: linux
    kubernetes.io/arch: amd64
  useHelmHooks: false
  jobAnnotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
  resources:
    requests:
      cpu: 10m
      memory: 10Mi
    limits:
      cpu: 500m
      memory: 500Mi

migrateDatabaseJob:
  nodeSelector:
    kubernetes.io/os: linux
    kubernetes.io/arch: amd64
  useHelmHooks: false
  jobAnnotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
  resources:
    requests:
      cpu: 10m
      memory: 10Mi
    limits:
      cpu: 500m
      memory: 500Mi

### SCHEDULER ####
scheduler:
  safeToEvict: false
  podDisruptionBudget:
    enabled: true
    config:
      maxUnavailable: 1
  nodeSelector:
    kubernetes.io/os: linux
    kubernetes.io/arch: amd64
  replicas: 2
  resources:
    requests:
      cpu: 1
      memory: 1Gi
    limits:
      cpu: 2
      memory: 2Gi
  logGroomerSidecar:
    resources:
      requests:
        cpu: 10m
        memory: 300Mi
      limits:
        cpu: 50m
        memory: 300Mi

### WEBSERVER ####
webserver:
  podAnnotations:
    ad.datadoghq.com/webserver.checks: |
      {
        "airflow": {
          "instances": [
            { "url": "http://%%host%%:8080" }
          ]
        }
      }
  podDisruptionBudget:
    enabled: true
    config:
      maxUnavailable: 1
  nodeSelector:
    kubernetes.io/os: linux
    kubernetes.io/arch: amd64
  replicas: 1
  resources:
    requests:
      cpu: 300m
      memory: 1Gi
    limits:
      cpu: 2
      memory: 2Gi

### WORKERS ####
workers:
  safeToEvict: false
  nodeSelector:
    kubernetes.io/os: linux
    kubernetes.io/arch: amd64
  replicas: 2
  podAnnotations:
    karpenter.sh/do-not-evict: "true"
  resources:
    requests:
      cpu: 1
      memory: 4Gi
    limits:
      cpu: 4
      memory: 8Gi

  logGroomerSidecar:
    resources:
      requests:
        cpu: 10m
        memory: 300Mi
      limits:
        cpu: 100m
        memory: 300Mi

  hpa:
    enabled: true
    # Minimum number of workers created by HPA
    minReplicaCount: 1
    # Maximum number of workers created by HPA
    maxReplicaCount: 10
    # Specifications for which to use to calculate the desired replica count
    metrics:
      - type: Resource
        resource:
          name: cpu
          target:
            type: Utilization
            averageUtilization: 80

### TRIGGERER ###
triggerer:
  safeToEvict: false
  nodeSelector:
    kubernetes.io/os: linux
    kubernetes.io/arch: amd64

  livenessProbe:
    timeoutSeconds: 45
  resources:
    requests:
      cpu: 25m
      memory: 512Mi
    limits:
      cpu: 100m
      memory: 1Gi
  logGroomerSidecar:
    resources:
      requests:
        cpu: 10m
        memory: 300Mi
      limits:
        cpu: 50m
        memory: 300Mi

### REDIS ###
redis:
  nodeSelector:
    kubernetes.io/os: linux
    kubernetes.io/arch: amd64
  safeToEvict: false
  # This password is meaningless. It just prevents an autogenerated password on each deployment potentially
  # breaking the connection Redis.
  password: swag123
  enabled: true
  resources:
    limits:
      cpu: 400m
      memory: 2Gi
    requests:
      cpu: 100m
      memory: 1Gi

### FLOWER ###
flower:
  enabled: false

### PGBOUNCER ###
pgbouncer:
  enabled: true
  nodeSelector:
    kubernetes.io/os: linux
    kubernetes.io/arch: amd64
  resources:
    requests:
      cpu: 10m
      memory: 5Mi
    limits:
      cpu: 50m
      memory: 50Mi
  metricsExporterSidecar:
    resources:
      requests:
        cpu: 5m
        memory: 5Mi
      limits:
        cpu: 50m
        memory: 50Mi

### INGRESS ###

ingress:
  enabled: false
  apiVersion: networking.k8s.io/v1
  web:
    host: pr{{number}}.airflow.homelab
    path: "/*"
    ## WARNING: requires Kubernetes 1.18 or later, use "kubernetes.io/ingress.class" annotation for older versions
    ingressClassName: "nginx-ingress"
    tls:
      enabled: false