apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperclip-data
  namespace: paperclip
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-hdd-storage
  volumeName: paperclip-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperclip-db-data
  namespace: paperclip
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-hdd-storage
  volumeName: paperclip-db-pv
