apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: metallb

resources:
  - namespace.yaml
  - ips.yaml

labels:
- pairs:
    app.kubernetes.io/name: metallb
    app.kubernetes.io/instance: metallb
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged

helmCharts:
  - name: metallb
    repo: https://metallb.github.io/metallb
    version: 0.15.3
    releaseName: metallb
    namespace: metallb
    valuesInline:
      controller:
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 50m
            memory: 50Mi
      speaker:
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 50m
            memory: 50Mi
