apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-config
  namespace: jellyfin
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-ssd-storage
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: downloads
  namespace: jellyfin
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-hdd-storage
  resources:
    requests:
      storage: 1Ti
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
  namespace: jellyfin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: radarr
  template:
    metadata:
      labels:
        app: radarr
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - cluster.local
      containers:
      - name: radarr
        image: lscr.io/linuxserver/radarr:latest
        env:
        - name: PUID
          value: "1000"  
        - name: PGID
          value: "1000" 
        - name: TZ
          value: "America/Los_Angeles"
        volumeMounts:
        # - name: config
        #   mountPath: /config
        - name: media
          mountPath: /data/movies
        # - name: downloads
        #   mountPath: /data/downloads
        ports:
        - containerPort: 7878
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: radarr-config
      - name: media
        persistentVolumeClaim:
          claimName: jellyfin-media
      - name: downloads
        persistentVolumeClaim:
          claimName: downloads
---
apiVersion: v1
kind: Service
metadata:
  name: radarr
  namespace: jellyfin
  labels:
    app: radarr
spec:
  ports:
    - port: 7878
      targetPort: 7878
      protocol: TCP
      name: http
  selector:
    app: radarr
