apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  repo: https://kubernetes.github.io/ingress-nginx
  chart: ingress-nginx
  targetNamespace: ingress-nginx
  valuesContent: |-
    controller:
      service:
        type: LoadBalancer
        loadBalancerIP: 192.168.1.151
      resources:
        requests:
          cpu: 100m
          memory: 90Mi
        limits:
          memory: 200Mi
