# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: coredns-custom
#   namespace: kube-system
# data:
#   home.server: |
#     . {
#         errors
#         health
#         kubernetes cluster.local in-addr.arpa ip6.arpa {
#             pods insecure
#             fallthrough in-addr.arpa ip6.arpa
#         }
#         hosts {
#             192.168.1.151 status.alexnorum.com
#             fallthrough
#         }
#         prometheus :9153
#         cache 30
#         loop
#         reload
#         loadbalance
#     }
