apiVersion: v1
kind: Service
metadata:
  name: ollama
  namespace: ollama
spec:
  ports:
    - port: 11434
      targetPort: 11434
      protocol: TCP
      name: http
---
apiVersion: v1
kind: Endpoints
metadata:
  name: ollama
  namespace: ollama
subsets:
  - addresses:
      - ip: "192.168.1.105"
    ports:
      - port: 11434
        protocol: TCP
        name: http
