apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

patches:
- target:
    kind: Deployment
    name: argocd-server
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 2
- target:
    kind: Deployment
    name: argocd-repo-server
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 2
- target:
    kind: StatefulSet
    name: argocd-application-controller
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 2

resources:
- namespace.yaml
- https://raw.githubusercontent.com/argoproj/argo-cd/v2.7.2/manifests/install.yaml
- ingress.yaml
- sealed-repo-secrets.yaml

configMapGenerator:
  - name: argocd-cm
    behavior: merge
    literals:
      - kustomize.buildOptions=--enable-helm
      - accounts.readonly=apiKey
  - name: argocd-rbac-cm
    behavior: merge
    literals:
      - policy.csv="g, readonly, role:readonly"
