apiVersion: ENC[AES256_GCM,data:5d4=,iv:sAwd4tjfhicRa/JyOWyuJ8bkUgegYh6dc7z0WsliGVc=,tag:4ZMRpHLo7vIqtpj4WVuG3Q==,type:str]
kind: ENC[AES256_GCM,data:Innr7oMV,iv:jBL+8LNJX5V/EfihvFuUm0tkR973FfoHmWitGe9aOAo=,tag:28Lv4pksqZHIQt0dGyTnVg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:lBk+TfxZdwcX/ZLs,iv:I1VGOyl/lprS+mtRHpe8BOZTA8Aoy1/HV+Czhbuhoxo=,tag:s/ZpDwi49WmaStLWmCBl+A==,type:str]
    namespace: ENC[AES256_GCM,data:Haf73qzE,iv:cAenXXJVHZZl4AaobpUsRRksZp1VeYvwUyzzJupYe9M=,tag:ZbfElCCPVjujCffBnwbcSw==,type:str]
    labels:
        argocd.argoproj.io/secret-type: ENC[AES256_GCM,data:ReFXl3WWJIrwiw==,iv:aGSXnBRWhiRIu+msv+635r0tOiu9/mvjafU8p4rNML4=,tag:dS4/jk8BEdgpfJGPq25PTQ==,type:str]
type: ENC[AES256_GCM,data:FwuDj5zt,iv:ZLs9c1wqVXmF+6On4FC2KB2vNU2OKmFUFQX5WkgdQX8=,tag:+fozrIbqXZMq1WZPH63zCw==,type:str]
stringData:
    type: ENC[AES256_GCM,data:ZvMb,iv:Gl2t+pf+a4O76G71VRkjXkbE8T+yCakWVq5BU9Ccp5M=,tag:JZ1naBh+w0Ytt0m0vxqipA==,type:str]
    url: ENC[AES256_GCM,data:suT/3XwAHfD1F6kz1BtNCP4Zxhmi1LLVcEINy+nNAWsa,iv:DgrxjxNXrcevWRE+QxPqcVYVbWTj0R/ZYdWwGIfqgs4=,tag:IOPAAPfRMVV0i4Yn+CehtQ==,type:str]
    sshPrivateKey: ENC[AES256_GCM,data:S1xIXCW2WAPjfa6F3ujHH5BUprmBAmzNh+T7xGjSAOkkywNyVto6kw0c80Vu/3Jo8Dz/n/M3CpxfxbWmoCejiZDNKKddJGivqLOhMm66h78R6sp/ZUQTg512yVeJd8jP3zyB6EygXpq2EjHpcKiWHDrSkJcizPYmontGePPD11pJIjZfMYZ58Sj7XuKQLra4B0/XHudCO/b4o+EVx+Xh6Dt/RQzAa5AAFy8YNQd7JSHDkoBmP9DNloUlLQgnbgq9zrX7JmzgPkIFuMRkJwHHiG5a7/cqSCg+PLxRVejg0gliGVfYExQeTOOt9Udt53DHXXjolsIKqQCbkZOszJZwALES7XIStWCEznPzb+/tL7NeEVWbJcDWDtjkhOYgT6P/AdSa75zbK8Zp0DjzIIMWbPjRSGeu5k9R9msmlPA1p61ebGhV6gdhHNDeQ5/FJrUepdBA0OR4GFmWGHcoROptubkjUUMN1VUXhbitcQPri0DAaw0nrMdTEbZHPNq5oM6Pq7Z0yPyF4PN78RVthMQjxs4112gde+9fXN44ivrtuUyYZVI=,iv:Q8pNUDQyXDg2fXg0pDE5uesyACNK0zGCfotlEAdtnOY=,tag:vCNb/DZ05CHdwOgROfFupg==,type:str]
sops:
    age:
        - recipient: age139l36fqzkzsl9rs7n5wxn9yngs0mdt06taktet96gm7uk9gq9aqqxukvps
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1OGxac0oyZngrb0lIZ3Mw
            K2YyMWVwOUpGZXBJMUVqUmk5ZHFROFBRVVQ0CnFoemVBYU9Kc2VtM1RlT0IwM2xq
            SEZjUUYxdEZvSHp4QnFaKzRiWW01MjgKLS0tIGhncmdZOFVIT1c5RVZnenVpRG5C
            SWRGOXIzVktZbTBtYkZGbTFoVWhiZzgKvqOkc7czDDJ5Ld+EzGNjSVcGOaISFf9+
            NhxZM6sruPK1V1yk+XU9RIVTenHyQYjS+a233Z8SKZQiEpoPOLDJ2w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-23T05:11:55Z"
    mac: ENC[AES256_GCM,data:QdLQyRCKPwPDx6XuNuf9/M3DJAgkeBYgMtfjxsZe19qXTggiGW4WKgLHuE6nrfVj6tC7YtpyJNYnTdgWcrXmA2h27/QnPZfHiUqqSS9RADMaICI9VMwyaDMdQgK1B4AhkaLOm+6xFT7DxoYO5Gku69tZW7DEm/mZUw0ekIPtjGI=,iv:zrQRAT8bPPn8ZRPkXy9o++sRIbEePbBZ4zE5mQB9T3E=,tag:4wGFFG+f5CzEQNTn9ESlfw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
