---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: argocd-secret
  namespace: argocd
spec:
  encryptedData:
    dex.authentik.clientSecret: AgB3oZ5rvgNTkZvynJfq6Q4RP90jqb1WEMhISE7+ZP05mWTxitwF3iMDHPlKAHIiwMenUDCwrCbQ8d7jreTd6yP7UzgJHH9fS6ZUIetMtQZ7WRX4njby1hz7cM23FrCKbM4z1HjQc5aAinnFv5Gv2gjQhXdFWKdnLy2W9fa1K6A6tBnYxv4SAJmaJdF5vXpiMBabWzmNMCV6GQsnsT9PKdMyrFC/OrPi7s0EbqmBMTahFXD1Inf2D3PVgcT1GS1qvC/L2bAL3WFIE8qJF/VGsrX0CEEft68vgDYk0/E6CoHGMUEhw7LADryjRDo1bZeTvhRw8q+mD4QoYKB79WAj0eiBQoGSiYWOoir2X/8z45ogwPjB+irD6qLkaDIlYbxqRd3aJ6OJ8jVAO5zKWNp3K1lM4g4SarwIhBOVM7yQsJf2fJOzhyoD+lF4SZCXAP897I3v9VC3CYBdcEiK/bCRknqcMR5jXm82hv8HLfkRfbvbGi8fegwjyhOMx3kUR7mrAK5fnFgX5bB/s938DhG4ceWNqRbrlhuCLBa/K1TQX20f9PoqwHV62sFpgXu0HcP/79T0hRL4ecdzMBqWjYbYbEDtZbJSWrfiTPCIVzi4ZnzLyER9CfaDOcaXkvCCvVWrsj1uTvonmusYLR60XURol56/2yLx9vVGTZvfoYScsNpVL8i/SJewDN9NhPMTJKA8jQ7vvJpZgzSGe93zp5ic4j5n7Mq5QNFqjp4ehpWM9BHtOrXp16HB0YeJgOASYyJ0rToAnWg8dJKY4lyFsfqisk0cVTxeBID7ysd4bfUNfbUZLAz8tUNZc6QRlvKxSvJxpKxLOEWnL304HYhpqSrBLacXImiAp17A2LKnu8MnFpIvsA==
  template:
    metadata:
      creationTimestamp: null
      name: argocd-secret
      namespace: argocd
    type: Opaque
