apiVersion: ENC[AES256_GCM,data:hMc=,iv:JPxu5v0qDzSR1wONLUpxxrEZtQotM5gGAL+5rez0z6E=,tag:IREjpyTRa7o5Us+UgGe1pw==,type:str]
kind: ENC[AES256_GCM,data:1ad+pbiA,iv:PyMfZxSfRvKgfGKQh1PJRwHJuOOyaR2IvFcvyoTPo/k=,tag:syTYl4lpYlYYLz2pj9VKEA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:nESyqNCelQ57eMsrlg==,iv:7cpNFxMi7d769fNAruqeAqz5P9W9RF0yNzFE8Rqdi7k=,tag:Y/FfapdfCpjFKIiz+5OFpg==,type:str]
    namespace: ENC[AES256_GCM,data:wag37VLR,iv:b6MauC7vZiqrvFE6Cc2yuTQSdMSi8F2dN+amaSFQU74=,tag:Yj8oGcXwTvmy4rhqJccuqw==,type:str]
    labels:
        app.kubernetes.io/name: ENC[AES256_GCM,data:IrIBMRLEGVhR4F7dTw==,iv:ekjJkH27QUkGb1ktyQMwP42JJ1xRY2ZoNoDkT9edEco=,tag:Cst8XK1E+erCzF4MP7Ul2g==,type:str]
        app.kubernetes.io/part-of: ENC[AES256_GCM,data:0hGLIc1G,iv:vLMSh4vBVykgZvpdHNHL/Areoh3wUGnvtW+e/IOfdgc=,tag:PS/2Y+8n6Fv8isuvizQc6A==,type:str]
type: ENC[AES256_GCM,data:G5jpkPrD,iv:8aAOsNOC0XGoBt5ZShpVK8Ks+paRxjX5OxTzXhf9FMk=,tag:IVCHOQWctcqNMDYREtFqzw==,type:str]
stringData:
    #ENC[AES256_GCM,data:cEJvg2rvc8oq5/N3u8kK8S1cWg9iCvKRXwGO6h0OrzvSW1iDz1sgor7XlXSP/kNz12tZEcsRZ/ky1MGHjWvFrwNBAssBWTyWuXZAhD04,iv:tQXmX09A0uJGIE3DHqZYDJ62cYHwIjrj/s7LwkIgMhU=,tag:eWHIBJa5q2P8Ns5hWmQnHQ==,type:comment]
    dex.authentik.clientSecret: ENC[AES256_GCM,data:gUMJeEwsHf01UyZOpOcWzPUFENAVmDhOlMbt3ibih2T1t0s=,iv:TPlsVCqqdInvRW6yKXYSe/E2Vc6w0EsKXqqcd4D94+4=,tag:86U0EQPPxwL+3U+470NicQ==,type:str]
sops:
    age:
        - recipient: age139l36fqzkzsl9rs7n5wxn9yngs0mdt06taktet96gm7uk9gq9aqqxukvps
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDMFFxV0hJak1ub2FlNGlG
            TUxuaG1VenRlTFhJd0tmRnBvUi9ScmpLS0dvCmM0Q3dkN2w1bE9lSm9ybmtwdWxX
            ZGgxdDQzU1pGSm5PR2hPMGg5dFROYjQKLS0tIDVQS1dzN0V0Y3JmYVkxWkRqQUQz
            dXNkMllUMUE2UUd3MlRJRXEwV3hIRkEKzgxvo49LX5fjHCQlxZQF8uuXZ3KNKCgR
            VI+6BKXmro6vQ24Oauhgyx2QIkAjk+DdXCxsYAT8d2MU95G1mp2fRw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-23T05:11:42Z"
    mac: ENC[AES256_GCM,data:I2h49nbXot4mhk6Hyrau4SHJt8dpIsZcyEwfRGxLLqY5n3m8xB8PFBKhIBGRD5GfrK7nXrjTh+i3VVqGXtKVTpKGEjh60qX9exiceHNLE2yIq+LaFJS02QTkLTRdW8MUhkifvAJkS0QO8JMkdxa3BO71wU6BIMdc2dSI7VMp8Qo=,iv:O/gy4sL6vFKI+De2oxWz4/W62wPY+4zELCW2KvZ5nKY=,tag:x9PXOlUYiRWq5r172QStxA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
