apiVersion: ENC[AES256_GCM,data:gF0=,iv:Z2GOYQj1GOiyHm6llJBTIRuA7Q/35W0M0n6ZCWELoLg=,tag:lSdssK1W1aB1u69t3MXwPQ==,type:str]
kind: ENC[AES256_GCM,data:zr1ZL3Zs,iv:2XEJtuYjDn4lYlMUDWdM9aHD9p6aLNkhpU4I+8vu+T0=,tag:FaBWMQvyH2FkeVM5F6LBvg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:CohJfDDjLDU/bqMsRQ==,iv:sjzkJHhZYkzRHdtBGSSIq5NFjo3KpcQzp0nW+nTiUVE=,tag:N2fD+Me2+exsSNU0SZq9Qw==,type:str]
    namespace: ENC[AES256_GCM,data:w8CvRYjK,iv:jpm+8qn77INU9ClKgpI3BX3qA4PXo9VLF/ZrIglPdVw=,tag:bfBgmZfVHEZuF714K6Pciw==,type:str]
    labels:
        app.kubernetes.io/name: ENC[AES256_GCM,data:fsSL/AZLBUaIoqpCDg==,iv:2QMccAKh3RK+34zMaRjjkUVaUct64reTw0d6LEMNIdk=,tag:B+gQaWivENgz0bxAvgK/Yw==,type:str]
        app.kubernetes.io/part-of: ENC[AES256_GCM,data:6TnpOb82,iv:srCIJmVQBOWpU+hQvejpdkG+o6HJCLgfnMFbuT0ACYg=,tag:QSS2Xit4c0x5W9KxECcJJg==,type:str]
type: ENC[AES256_GCM,data:qIkI/lON,iv:vmXIpVNqSaYLnnIu7XAXGpi6vjwyXOI+jW2P9p/OPIY=,tag:nYsoTFydDV6L5yVvm553dQ==,type:str]
stringData:
    dex.authentik.clientSecret: ENC[AES256_GCM,data:lppbnDbU1EwNtr6SPVDrxvh4utbKr3JwOPYZlbsjLaeU0eyjiHm+5ekquIM=,iv:j8AH3OwUiRRVYYWl0NbxyuZLJt2VFEndh/+FzoyJXcM=,tag:P6gUdsrf16v6xWwQtyv+xQ==,type:str]
sops:
    age:
        - recipient: age139l36fqzkzsl9rs7n5wxn9yngs0mdt06taktet96gm7uk9gq9aqqxukvps
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0NjJMYlROZUUyL2dIdHg3
            ekNoalh5b3E2N3lRSS84U0prV0dIVjFIWTA0CkUyemFsOTJXb3ZEM0pVMlBYTGwx
            RDVnNUdWSEpFSmMyeEhucVB1ZWNnMXcKLS0tIHJuRTZFWHkwcVpJbVdCLzVTY2lP
            cXBxeVZpNDJMelJmRXlISHVsc2VmdkEKjVG+yZyiNHWEY12dF77Xl6ha4nMcF66u
            6gC1wIHgQaUU8rJoCD5R1Jb0Th0iLNFASJsDCnqW1zot554EwzxYmg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-26T00:16:34Z"
    mac: ENC[AES256_GCM,data:28khz/PEcfRn+zlbUHzBS71QQ4NLZuzyx1wys6h7F4ptkNmS+7hKy7cy6G+H2MDH0aiGHXJ4thycQISzOYMfypgo7CvHgJUx65xTaooWY/Z0JZ2NNVx0Lf6Xcc4vMglOqCH9XEZsxnLbtBV8t1bmckxFUfDnt/KKIBDMDOQEkQ8=,iv:yTM/tUwXbWhCK5GKqaRbAJFNl9Lf0TOXEzwbJVvRf8Y=,tag:2E4GAkMxV9F+BiCTqYgm2Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
