apiVersion: apps/v1
kind: Deployment
metadata:
  name: marabot
  namespace: marabot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: marabot
  template:
    metadata:
      labels:
        app: marabot
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: marabot
        image: anorum/marabot:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: marabot-secrets
              key: openai-api-key
        ports:
        - containerPort: 8000
          name: http
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
