apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: alex-website

resources:
- namespace.yaml
- deployment.yaml
- ingress.yaml
images:
- name: ghcr.io/anorum/alex-website:latest
  newName: ghcr.io/anorum/alex-website
  newTag: sha-4be8c2e
