apiVersion: v1
kind: Secret
metadata:
    name: step-ca-issuer
    namespace: step-ca
type: Opaque
stringData:
    intermediate_ca_key: ENC[AES256_GCM,data:78K4mVu5C8PYHFg41Rk+NnyocbBaJEa8pAOPonwcN0Rvgbws4KJZnOzNtfLdYgBFg1mffdD1brvNDPDztDwdROalMWkRZGjUwq5wx+6MPHDT0umyNESxac21FXzrnRaZlk9NuJycTuyvdh8dyiGpJfHJ3SXJuk05HoTUv4mq6zDDFuWbNr9RPU6eFM2MHxbJO1AijlI/ZJy06yaH/nCoXGX8ytCY6xNQyZDaD1d8EC0K5o2Qh5uWcgHaopKZ/eoR6YKZKA+hpS64I73wE8/Iio8cMiR3EsP+qgUDw0zoZQAbTUDDgJU5wRE6+PwsiVLsAWchFA/9Bfp0NPkObMcOq12uH4VJ/FsN4ZgKb85axb3CeCkEsu89gge2yyOpV4bMiLAKC5wxXClmgThhlEzTblLIdK4vVyOSZnQ=,iv:9G04hs5iciQQCXfbIkDsYtqS6DG9fp7On2a6ayF975s=,tag:suuKmgiEF0eN/7OEQum2mQ==,type:str]
    password: ENC[AES256_GCM,data:B5fKYETIw4aWs15qB1nt+d/beoOcgKET33zm1OLBtURRlUut4skraJ0wOkPrNfiJs1FgEIow+7maUUQHNfi6lFM=,iv:LcRPhcugMZC7XtKApxrSaaYblo+zPTVbVTmCYlqu14s=,tag:5SOo3xJ5H3hwNqjB7HpiVw==,type:str]
sops:
    age:
        - recipient: age139l36fqzkzsl9rs7n5wxn9yngs0mdt06taktet96gm7uk9gq9aqqxukvps
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmc1VFdXcvL1FBMDhkRzJm
            Z3RvT1FLMHhzdGMvbUxTcVFRRDBtVHphK2hVCm9BOHRYQjIwV1hqaWIrRnJsWGpr
            Q3Ezcmp1K0l6bUpxdXFYYW5UOXlCUkEKLS0tIEdieG9pVSt2R0xvenN1R1ZLaE54
            amhML2VEUjFrSVN1WkxTK0RRQ2FsdFUKLgB8GDe3HlztLkeDW6/Gc8IcgGWBhA+7
            BQhwpuQFKxZ2tI/1oQjWhsaDD+4PG7/SIgDWVN3wjbAkftEGcZ38sw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-19T17:23:00Z"
    mac: ENC[AES256_GCM,data:fGTH1gtyZv2x4XIr9m/dgzaluyMYip7kvj7RGC2la3ZVymfD8C/lZaHJ4vNVugdJmos6QtE+fAAa+V9CAWsneagzTqlHopY9mpOu/gdabHemgjzXnPGCtHWfLROov3BsgL36njkt8+dEgTjTy/SnjPh5BE/G8HaOwkKGYwLaRv8=,iv:xwxljpHDp8t9IHwHYTPemrdBiTGX9+QnkUdeIYGoMm8=,tag:MbVXDaTBTSpD/uPkHL2h7w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
