apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  annotations:
    akuity.io/refreshedAt: "25"
  name: airflow-pr
spec:
  generators:
    - pullRequest:
        github:
          owner: anorum
          repo: homelab
          tokenRef:
            secretName: github-token
            key: token
          labels:
            - prenv
        requeueAfterSeconds: 60
  template:
    metadata:
      name: airflow-ephenv-{{number}}
    spec:
      destination:
        namespace: test
        server: https://kubernetes.default.svc
      project: default

      # source:
      #   helm:
      #     parameters:
      #       - name: "images.airflow.tag"
      #         value: "{{head_sha}}"
      #       - name:  "ingress.web.annotations.external-dns.alpha.kubernetes.io/hostname"
      #         value:  pr{{number}}.airflow.homelab
      #       - name: "ingress.web.host"
      #         value: pr{{number}}.airflow.homelab
      #   ## what path should argo look at in your manifest repo for deployment
      #   path: airflow
      #   ## Your deployment repo, where your k8/kustomize manifests are located
      #   repoURL: git@github.com:anorum/homelab.git

      sources:
        - repoURL: git@github.com:anorum/homelab.git
          ref: values
          path: airflow
          kustomize:
            commonLabels:
              app.kubernetes.io/instance: "pull_request-{{number}}"
            namePrefix: "pr{{number}}-"
        - repoURL: https://airflow.apache.org
          targetRevision: 1.15.0  
          chart: airflow
          helm:
            releaseName: pr
            valueFiles:
              - $values/airflow/values-common.yaml
            values: |
              scheduler:
                replicas: 1
              env:
                - name: "AIRFLOW__WEBSERVER__BASE_URL"
                  value: "pr{{number}}.airflow.homelab"
                - name: "AIRFLOW__WEBSERVER__INSTANCE_NAME"
                  value: "TESTING PR{{number}}"

      syncPolicy: {}
