apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:anorum/homelab.git
    targetRevision: HEAD
    path: argo-apps
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: adguard
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:anorum/homelab.git
    targetRevision: HEAD
    path: adguard
  destination:
    server: https://kubernetes.default.svc
    namespace: adguard
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: uptime-kuma
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:anorum/homelab.git
    targetRevision: HEAD
    path: uptime-kuma
  destination:
    server: https://kubernetes.default.svc
    namespace: uptime-kuma
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflared
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:anorum/homelab.git
    targetRevision: HEAD
    path: cloudflared
  destination:
    server: https://kubernetes.default.svc
    namespace: cloudflared
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:anorum/homelab.git
    targetRevision: HEAD
    path: cert-manager
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:anorum/homelab.git
    targetRevision: HEAD
    path: external-dns
  destination:
    server: https://kubernetes.default.svc
    namespace: external-dns
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:anorum/homelab.git
    targetRevision: HEAD
    path: metallb
  destination:
    server: https://kubernetes.default.svc
    namespace: metallb
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:anorum/homelab.git
    targetRevision: HEAD
    path: ingress-nginx
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:anorum/homelab.git
    targetRevision: HEAD
    path: prometheus
  destination:
    server: https://kubernetes.default.svc
    namespace: prometheus
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homepage
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:anorum/homelab.git
    targetRevision: HEAD
    path: homepage
  destination:
    server: https://kubernetes.default.svc
    namespace: homepage
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:anorum/homelab.git
    targetRevision: HEAD
    path: external-secrets
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets