apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: adguard
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:anorum/homelab.git
    targetRevision: HEAD
    path: adguard
  destination:
    server: https://kubernetes.default.svc
    namespace: adguard
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: uptime-kuma
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:anorum/homelab.git
    targetRevision: HEAD
    path: uptime-kuma
  destination:
    server: https://kubernetes.default.svc
    namespace: uptime-kuma
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflared
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:anorum/homelab.git
    targetRevision: HEAD
    path: cloudflared
  destination:
    server: https://kubernetes.default.svc
    namespace: cloudflared
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:anorum/homelab.git
    targetRevision: HEAD
    path: metallb
  destination:
    server: https://kubernetes.default.svc
    namespace: metallb
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:anorum/homelab.git
    targetRevision: HEAD
    path: ingress-nginx
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:anorum/homelab.git
    targetRevision: HEAD
    path: prometheus
  destination:
    server: https://kubernetes.default.svc
    namespace: prometheus
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homepage
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:anorum/homelab.git
    targetRevision: HEAD
    path: homepage
  destination:
    server: https://kubernetes.default.svc
    namespace: homepage
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:anorum/homelab.git
    targetRevision: HEAD
    path: sealed-secrets
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jellyfin
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:anorum/homelab.git
    targetRevision: HEAD
    path: jellyfin
  destination:
    server: https://kubernetes.default.svc
    namespace: jellyfin
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: storage
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:anorum/homelab.git
    targetRevision: HEAD
    path: storage
  destination:
    server: https://kubernetes.default.svc
    namespace: storage
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: home-assistant
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:anorum/homelab.git
    targetRevision: HEAD
    path: home-assistant
  destination:
    server: https://kubernetes.default.svc
    namespace: home-assistant
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentik
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:anorum/homelab.git
    targetRevision: HEAD
    path: authentik
  destination:
    server: https://kubernetes.default.svc
    namespace: authentik
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: registry
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:anorum/homelab.git
    targetRevision: HEAD
    path: registry
  destination:
    server: https://kubernetes.default.svc
    namespace: registry
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: marabot
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:anorum/homelab.git
    targetRevision: HEAD
    path: marabot
  destination:
    server: https://kubernetes.default.svc
    namespace: marabot
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mealie
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:anorum/homelab.git
    targetRevision: HEAD
    path: mealie
  destination:
    server: https://kubernetes.default.svc
    namespace: mealie
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alex-api
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:anorum/homelab.git
    targetRevision: HEAD
    path: alex-api
  destination:
    server: https://kubernetes.default.svc
    namespace: alex-api
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alex-website
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:anorum/homelab.git
    targetRevision: HEAD
    path: website
  destination:
    server: https://kubernetes.default.svc
    namespace: alex-website
