apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  annotations:
    akuity.io/refreshedAt: "25"
  name: airflow-pr
spec:
  generators:
    - pullRequest:
        github:
          owner: anorum
          repo: homelab
          tokenRef:
            secretName: github-token
            key: token
          labels:
            - prenv
        requeueAfterSeconds: 60
  template:
    metadata:
      name: airflow-ephenv-{{number}}
    spec:
      destination:
        namespace: test
        server: https://kubernetes.default.svc
      project: default

      sources:
        - repoURL: git@github.com:anorum/homelab.git
          path: airflow
          kustomize:
            commonLabels:
              app.kubernetes.io/instance: "pull_request-{{number}}"
            namePrefix: "pr{{number}}-"
      syncPolicy: {}
